package projectecg.models;

import java.sql.Timestamp;

/**
 * Patient: Entity model representing a patient record in the database
 * Corresponds to the 'patients' table schema
 */
public class Patient {
    private int id;
    private String name;
    private String sex;
    private String birthdate;
    private int age;
    private double weight;
    private double height;
    private String arrhythmiaLabel;
    private double confidenceScore;
    private String aiRecommendation;
    private Timestamp analysisDate;
    private Timestamp createdAt;
    
    // Clinical Parameters
    private int heartRate;
    private double prInterval;
    private double qrsDuration;
    private double qtcInterval;
    private double stDeviation;

    // New Demographic Fields
    private String tempatLahir;
    private String nik;
    private String alamat;
    private String golDarah;
    private String pekerjaan;
    private String kewarganegaraan;
    private String statusKawin;
    private String agama;

    // ========== CONSTRUCTORS ==========

    /**
     * Default constructor
     */
     public Patient() {
     }

    /**
     * Constructor for new patient (without ID, auto-generated by DB)
     */
    public Patient(String name, String sex, String birthdate, int age,
                   double weight, double height) {
        this.name = name;
        this.sex = sex;
        this.birthdate = birthdate;
        this.age = age;
        this.weight = weight;
        this.height = height;
    }

    /**
     * Constructor with analysis results
     */
    public Patient(String name, String sex, String birthdate, int age,
                   double weight, double height, String arrhythmiaLabel,
                   double confidenceScore, String aiRecommendation) {
        this(name, sex, birthdate, age, weight, height);
        this.arrhythmiaLabel = arrhythmiaLabel;
        this.confidenceScore = confidenceScore;
        this.aiRecommendation = aiRecommendation;
        this.analysisDate = new Timestamp(System.currentTimeMillis());
    }

    /**
     * Constructor with complete analysis results and clinical parameters
     */
    public Patient(String name, String sex, String birthdate, int age,
                   double weight, double height, String arrhythmiaLabel,
                   double confidenceScore, String aiRecommendation, int heartRate,
                   double prInterval, double qrsDuration, double qtcInterval, double stDeviation) {
        this(name, sex, birthdate, age, weight, height);
        this.arrhythmiaLabel = arrhythmiaLabel;
        this.confidenceScore = confidenceScore;
        this.aiRecommendation = aiRecommendation;
        this.heartRate = heartRate;
        this.prInterval = prInterval;
        this.qrsDuration = qrsDuration;
        this.qtcInterval = qtcInterval;
        this.stDeviation = stDeviation;
        this.analysisDate = new Timestamp(System.currentTimeMillis());
    }

    // ========== GETTERS & SETTERS ==========

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public double getHeight() {
        return height;
    }

    public void setHeight(double height) {
        this.height = height;
    }

    public String getArrhythmiaLabel() {
        return getArrhythmiaLabelDescription();
    }

    public String getArrhythmiaLabelCode() {
        return arrhythmiaLabel;
    }

    public void setArrhythmiaLabel(String arrhythmiaLabel) {
        this.arrhythmiaLabel = arrhythmiaLabel;
    }

    public double getConfidenceScore() {
        return confidenceScore;
    }

    public void setConfidenceScore(double confidenceScore) {
        this.confidenceScore = confidenceScore;
    }

    public String getAiRecommendation() {
        return aiRecommendation;
    }

    public void setAiRecommendation(String aiRecommendation) {
        this.aiRecommendation = aiRecommendation;
    }

    public Timestamp getAnalysisDate() {
        return analysisDate;
    }

    public void setAnalysisDate(Timestamp analysisDate) {
        this.analysisDate = analysisDate;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public int getHeartRate() {
        return heartRate;
    }

    public void setHeartRate(int heartRate) {
        this.heartRate = heartRate;
    }

    public double getPrInterval() {
        return prInterval;
    }

    public void setPrInterval(double prInterval) {
        this.prInterval = prInterval;
    }

    public double getQrsDuration() {
        return qrsDuration;
    }

    public void setQrsDuration(double qrsDuration) {
        this.qrsDuration = qrsDuration;
    }

    public double getQtcInterval() {
        return qtcInterval;
    }

    public void setQtcInterval(double qtcInterval) {
        this.qtcInterval = qtcInterval;
    }

    public double getStDeviation() {
        return stDeviation;
    }

    public void setStDeviation(double stDeviation) {
        this.stDeviation = stDeviation;
    }

    public String getArrhythmiaLabelDescription() {
        if (arrhythmiaLabel == null || arrhythmiaLabel.trim().isEmpty()) {
            return "Unknown";
        }
        return projectecg.GeminiHealthAdvisor.getClassificationDescription(arrhythmiaLabel.trim());
    }

    // ========== UTILITY METHODS ==========

    @Override
    public String toString() {
        return "Patient{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", sex='" + sex + '\'' +
                ", age=" + age +
                ", weight=" + weight +
                ", height=" + height +
                ", arrhythmiaLabel='" + arrhythmiaLabel + '\'' +
                ", confidenceScore=" + confidenceScore +
                ", heartRate=" + heartRate +
                ", prInterval=" + prInterval +
                ", qrsDuration=" + qrsDuration +
                ", qtcInterval=" + qtcInterval +
                ", stDeviation=" + stDeviation +
                ", createdAt=" + createdAt +
                '}';
    }

    /**
     * Check if patient has analysis results
     */
    public boolean hasAnalysisResults() {
        return arrhythmiaLabel != null && confidenceScore > 0;
    }

    /**
     * Get BMI (Body Mass Index)
     */
    public double calculateBMI() {
        if (height <= 0 || weight <= 0) {
            return 0;
        }
        double heightInMeters = height / 100.0;
        return weight / (heightInMeters * heightInMeters);
    }

    // New Demographics Getters & Setters
    public String getTempatLahir() { return tempatLahir; }
    public void setTempatLahir(String tempatLahir) { this.tempatLahir = tempatLahir; }

    public String getNik() { return nik; }
    public void setNik(String nik) { this.nik = nik; }

    public String getAlamat() { return alamat; }
    public void setAlamat(String alamat) { this.alamat = alamat; }

    public String getGolDarah() { return golDarah; }
    public void setGolDarah(String golDarah) { this.golDarah = golDarah; }

    public String getPekerjaan() { return pekerjaan; }
    public void setPekerjaan(String pekerjaan) { this.pekerjaan = pekerjaan; }

    public String getKewarganegaraan() { return kewarganegaraan; }
    public void setKewarganegaraan(String kewarganegaraan) { this.kewarganegaraan = kewarganegaraan; }

    public String getStatusKawin() { return statusKawin; }
    public void setStatusKawin(String statusKawin) { this.statusKawin = statusKawin; }

    public String getAgama() { return agama; }
    public void setAgama(String agama) { this.agama = agama; }
}
