/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projectecg;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


public class analyzepanel extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(analyzepanel.class.getName());
    // Tambahkan ini di dekat deklarasi variabel lain
    private javax.swing.JLabel lblFormulaName;
    // ========== STORAGE FIELDS FOR ANALYSIS RESULTS ==========
    // WHY: We need to store analysis data so we can export to CSV later
    private ECGAnalyzer currentAnalyzer;
    private String patientName = "N/A";
    private String patientID = "N/A";
    private String classificationResult = "N/A";
    private double confidenceRate = 0.0;
    private String riskLevel = "N/A";
    private double heartRateAvg = 0.0;
    
    // ========== PATIENT DEMOGRAPHIC INFORMATION ==========
    // WHY: Include comprehensive patient info in CSV export for clinical context
    private String patientSex = "N/A";
    private int patientAge = 0;
    private String patientBirthdate = "N/A";
    
    // ========== ANALYSIS MODE FLAG ==========
    // WHY: Distinguish between Model Classification (shows health advice) and Classic Analysis (measurements only)
    private boolean isClassicAnalysis = false;
    
    // ========== QWEN AI STRUCTURED ADVICE (NEW) ==========
    // WHY: Store Qwen-generated advice from Python backend for display and export
    private String qwenInterpretation = "";
    private String qwenMedicalAction = "";
    private String qwenLifestyle = "";
    private String qwenDisclaimer = "";
    private boolean hasQwenAdvice = false;

    public analyzepanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyFieldStyling(); // Hanya styling, TIDAK mengubah layout
    }
    
    private void optimizeLayout() {
    // 1. Matikan edit agar read-only
        javax.swing.JTextField[] fields = {
            jTextField1, jTextField2, jTextField3, jTextField5, 
            jTextField6, jTextField7, jTextField8, jTextField9, jTextField10, 
            jTextField11, jTextField12, jTextField13
        };
        
        for (javax.swing.JTextField f : fields) {
            if (f != null) {
                f.setEditable(false);
                f.setBackground(new java.awt.Color(245, 245, 245)); 
                f.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                
                // Set ukuran default untuk semua kotak (misal untuk nilai interval pendek)
                f.setPreferredSize(new java.awt.Dimension(80, 25)); 
            }
        }
        
        if (jTextField1 != null) {
            jTextField1.setPreferredSize(new java.awt.Dimension(300, 25)); 
        }
        
        // jTextField2 adalah "Fs". 60 pixel cukup.
        if (jTextField2 != null) {
            jTextField2.setPreferredSize(new java.awt.Dimension(60, 25));
        }
        
        // 3. Panggil pack agar window menyesuaikan konten
        this.pack();
        
        // 4. Tengahkan window
        this.setLocationRelativeTo(getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        lblQRSDuration = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnHealthAdvice = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblPRSegment = new javax.swing.JLabel();
        lblSTInterval = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPR = new javax.swing.JTextField();
        jTextFieldSTInterval = new javax.swing.JTextField();
        jTextFieldSTSegment = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jtxtSDNN = new javax.swing.JTextField();
        jtxtRMSSD = new javax.swing.JTextField();
        jtxtNN50 = new javax.swing.JTextField();
        jtxtpNN50 = new javax.swing.JTextField();
        jtxtSD1 = new javax.swing.JTextField();
        jtxtSD2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Data Window : ");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel2.setText("s");

        jLabel3.setText("Fs :");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel4.setText("Hz");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEAK COUNT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setText("R Peaks : ");

        jLabel6.setText("P Peaks : ");

        jLabel7.setText("T Peaks : ");

        jTextField8.addActionListener(this::jTextField8ActionPerformed);

        jTextField9.addActionListener(this::jTextField9ActionPerformed);

        jTextField10.addActionListener(this::jTextField10ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HEART RATE & RR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel8.setText("HR Avg      : ");

        jLabel10.setText("RR Avg       : ");

        jLabel11.setText("RR Min        :");

        jLabel12.setText("RR Max       : ");

        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jTextField6.addActionListener(this::jTextField6ActionPerformed);

        jTextField7.addActionListener(this::jTextField7ActionPerformed);

        jLabel20.setText("BPM");

        jLabel22.setText("ms");

        jLabel23.setText("ms");

        jLabel24.setText("ms");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(jTextField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(73, 73, 73))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INTERVAL MEASUREMENTS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel13.setText("PR Avg        : ");

        jLabel16.setText("QT Avg       : ");

        jLabel17.setText("QTc Avg     : ");

        jTextField11.addActionListener(this::jTextField11ActionPerformed);

        jTextField12.addActionListener(this::jTextField12ActionPerformed);

        jTextField13.addActionListener(this::jTextField13ActionPerformed);

        lblQRSDuration.setText("QRS Avg     :");

        jTextField14.addActionListener(this::jTextField14ActionPerformed);

        jLabel25.setText("ms");

        jLabel26.setText("ms");

        jLabel27.setText("ms");

        jLabel28.setText("ms");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(lblQRSDuration)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQRSDuration)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Download");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        btnHealthAdvice.setText("View Health Advice");
        btnHealthAdvice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHealthAdvice.addActionListener(this::btnHealthAdviceActionPerformed);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ECG SEGMENTS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblPRSegment.setText("PR Segment   :");

        lblSTInterval.setText("ST Interval      :");

        jLabel14.setText("ST Amplitude :");

        jLabel15.setText("ms");

        jLabel18.setText("ms");

        jLabel19.setText("mV");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSTInterval)
                            .addComponent(lblPRSegment)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSTSegment, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSTInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPR, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRSegment)
                    .addComponent(jTextFieldPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSTInterval)
                    .addComponent(jTextFieldSTInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldSTSegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HRV TIME DOMAIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel9.setText("SDNN    :");

        jLabel21.setText("RMSSD  :");

        jLabel29.setText("NN50     :");

        jLabel30.setText("pNN50   :");

        jLabel31.setText("SD1       :");

        jLabel32.setText("SD2       : ");

        jtxtpNN50.addActionListener(this::jtxtpNN50ActionPerformed);

        jtxtSD1.addActionListener(this::jtxtSD1ActionPerformed);

        jtxtSD2.addActionListener(this::jtxtSD2ActionPerformed);

        jLabel33.setText("ms");

        jLabel34.setText("ms");

        jLabel35.setText("%");

        jLabel36.setText("ms");

        jLabel37.setText("ms ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtSDNN, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRMSSD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtNN50, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtpNN50, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtSD1)
                            .addComponent(jtxtSD2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtSDNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jtxtRMSSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jtxtNN50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jtxtpNN50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jtxtSD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jtxtSD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHealthAdvice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(133, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClose, btnHealthAdvice, jButton2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHealthAdvice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Cek apakah ada data analisis
        if (currentAnalyzer == null && classificationResult.equals("N/A")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No analysis results to export!\nPlease run analysis first.", 
                "Export Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Buat file chooser dialog
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Save ECG Analysis Results");
        
        // Default filename dengan timestamp (tanpa ekstensi dulu)
        String timestamp = new java.text.SimpleDateFormat("yyyyMMdd_HHmmss").format(new java.util.Date());
        String defaultFileName = "ECG_Analysis_" + timestamp;
        fileChooser.setSelectedFile(new java.io.File(defaultFileName));
        
        // Pilihan ekstension (PDF & CSV)
        javax.swing.filechooser.FileNameExtensionFilter filterPDF = new javax.swing.filechooser.FileNameExtensionFilter("PDF Documents (*.pdf)", "pdf");
        javax.swing.filechooser.FileNameExtensionFilter filterCSV = new javax.swing.filechooser.FileNameExtensionFilter("CSV Files (*.csv)", "csv");
        
        fileChooser.addChoosableFileFilter(filterPDF);
        fileChooser.addChoosableFileFilter(filterCSV);
        fileChooser.setFileFilter(filterPDF); // Jadikan PDF sebagai pilihan default (pertama muncul)
        
        // Tampilkan dialog save
        int result = fileChooser.showSaveDialog(this);
        
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            
            // Cek filter mana yang dipilih oleh user
            javax.swing.filechooser.FileFilter selectedFilter = fileChooser.getFileFilter();
            
            // Jika CSV dipilih
            if (selectedFilter == filterCSV || filePath.toLowerCase().endsWith(".csv")) {
                if (!filePath.toLowerCase().endsWith(".csv")) {
                    filePath += ".csv";
                }
                java.io.File csvFile = new java.io.File(filePath);
                
                // Ambil nilai interval dari Text Field 
                int rPeaks = 0, pPeaks = 0, tPeaks = 0;
                double rrInterval = 0.0, prInterval = 0.0, qtInterval = 0.0, qtcInterval = 0.0;
                
                try {
                    rPeaks = Integer.parseInt(jTextField8.getText());
                    pPeaks = Integer.parseInt(jTextField9.getText());
                    tPeaks = Integer.parseInt(jTextField10.getText());
                    rrInterval = Double.parseDouble(jTextField5.getText());
                    prInterval = Double.parseDouble(jTextField11.getText()) * 1000;  
                    qtInterval = Double.parseDouble(jTextField12.getText()) * 1000;  
                    qtcInterval = Double.parseDouble(jTextField13.getText()) * 1000; 
                } catch (NumberFormatException e) {
                    rPeaks = 75; pPeaks = 74; tPeaks = 75; rrInterval = 833.33;
                    prInterval = 120.0; qtInterval = 400.0; qtcInterval = 410.0;
                }
                
                String healthAdviceText = generateHealthAdvice();
                boolean success = CSVExporter.exportToCSVWithDemographics(
                    csvFile, patientName, patientID, patientSex, patientBirthdate,
                    String.valueOf(patientAge), "-", "-",
                    classificationResult, confidenceRate * 100, riskLevel, 0,  
                    rPeaks, pPeaks, tPeaks, rrInterval, healthAdviceText,
                    prInterval, qtInterval, qtcInterval 
                );
                
                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "✓ CSV saved to:\n" + csvFile.getAbsolutePath(), "Export Successful", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error saving CSV file.", "Export Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } 
            // Jika PDF dipilih
            else {
                if (!filePath.toLowerCase().endsWith(".pdf")) {
                    filePath += ".pdf";
                }
                
                try {
                    projectecg.MainDashboard parent = (projectecg.MainDashboard) this.getParent();

                    // 1. Ambil data asli & Lengkapi jadi 12-lead
                    java.util.List<double[]> rawLeads = parent.getProcessedLeadsData();
                    java.util.List<double[]> full12Leads = parent.generate12LeadData(rawLeads);

                    // 2. BUNGKUS SEMUA DATA KE DALAM Map UNTUK DIKIRIM KE PDF EXPORTER
                    java.util.Map<String, String> pdfData = new java.util.HashMap<>();

                    // -- Data untuk Tabel 1: Demografi Pasien
                    pdfData.put("name", (this.patientName != null && !this.patientName.isEmpty()) ? this.patientName : "-");
                    pdfData.put("id", (this.patientID != null && !this.patientID.isEmpty()) ? this.patientID : "-");
                    pdfData.put("age", String.valueOf(this.patientAge));
                    pdfData.put("dob", this.patientBirthdate != null ? this.patientBirthdate : "-");
                    pdfData.put("sex", this.patientSex != null ? this.patientSex : "-");

                    // -- Data untuk Tabel 2: Hasil Analisis Model
                    String deskripsiPanjang = projectecg.GeminiHealthAdvisor.getClassificationDescription(this.classificationResult);
                    pdfData.put("hr", this.heartRateAvg > 0 ? String.format("%.1f", this.heartRateAvg) : "-");
                    pdfData.put("diagnosis", deskripsiPanjang);
                    pdfData.put("confidence", String.format("%.1f", this.confidenceRate * 100));
                    pdfData.put("risk", this.riskLevel != null ? this.riskLevel : "-");

                    // -- Data untuk Tabel 3: Metrics (Mengambil data dari TextBox UI)
                    pdfData.put("rrAvg", jTextField5.getText());
                    pdfData.put("rrMin", jTextField6.getText());
                    pdfData.put("rrMax", jTextField7.getText());
                    
                    pdfData.put("rPeaks", jTextField8.getText());
                    pdfData.put("pPeaks", jTextField9.getText());
                    pdfData.put("tPeaks", jTextField10.getText());
                    
                    pdfData.put("prAvg", jTextField11.getText());
                    pdfData.put("qrsAvg", jTextField12.getText());
                    pdfData.put("qtAvg", jTextField13.getText());
                    pdfData.put("qtcAvg", jTextField14.getText());
                    
                    pdfData.put("prSeg", jTextFieldPR.getText());
                    pdfData.put("stInt", jTextFieldSTInterval.getText());
                    pdfData.put("stSeg", jTextFieldSTSegment.getText());
                    
                    pdfData.put("sdnn", jtxtSDNN.getText());
                    pdfData.put("rmssd", jtxtRMSSD.getText());
                    pdfData.put("nn50", jtxtNN50.getText());
                    pdfData.put("pnn50", jtxtpNN50.getText());
                    pdfData.put("sd1", jtxtSD1.getText());
                    pdfData.put("sd2", jtxtSD2.getText());

                    // Ambil data yang dipilih
                    String formulaName = parent.qtcFormula != null ? parent.qtcFormula : "Bazett";
                    pdfData.put("formula", formulaName);
                    pdfData.put("speed", parent.getSpeedSetting());
                    pdfData.put("gain", parent.getGainSetting());
                    pdfData.put("filter", parent.getFilterSetting());

                    // Kirim Saran Kesehatan mentah (Disclaimer akan otomatis dibuang oleh Exporter)
                    pdfData.put("advice", generateHealthAdvice());

                    // 3. Panggil PDFExporter dengan Map
                    boolean success = projectecg.PDFExporter.generateReport(
                        filePath, pdfData, full12Leads, parent.getCurrentFs()
                    );
                    
                    if (success) {
                        javax.swing.JOptionPane.showMessageDialog(this, "✓ Laporan PDF medis berhasil disimpan ke:\n" + filePath, "Export Successful", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuat PDF. Pastikan file tidak sedang dibuka.", "Export Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem saat mengekspor ke PDF.", "Export Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    // Menutup jendela dialog ini
    this.dispose();        
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * Show health advice and patient information in a message dialog
     * WHY: User can view health advice without having to export CSV
     */
    private void btnHealthAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealthAdviceActionPerformed
        String patientSummary = getPatientSummary();
        String healthAdvice = generateHealthAdvice();
        
        String fullMessage = patientSummary + "\n" + healthAdvice;
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            fullMessage,
            "Patient Health Report",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHealthAdviceActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jtxtpNN50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpNN50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpNN50ActionPerformed

    private void jtxtSD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSD1ActionPerformed

    private void jtxtSD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSD2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                analyzepanel dialog = new analyzepanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHealthAdvice;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldPR;
    private javax.swing.JTextField jTextFieldSTInterval;
    private javax.swing.JTextField jTextFieldSTSegment;
    private javax.swing.JTextField jtxtNN50;
    private javax.swing.JTextField jtxtRMSSD;
    private javax.swing.JTextField jtxtSD1;
    private javax.swing.JTextField jtxtSD2;
    private javax.swing.JTextField jtxtSDNN;
    private javax.swing.JTextField jtxtpNN50;
    private javax.swing.JLabel lblPRSegment;
    private javax.swing.JLabel lblQRSDuration;
    private javax.swing.JLabel lblSTInterval;
    // End of variables declaration//GEN-END:variables

    private void colorCodeSTSegment(double stValue) {
        if (jTextFieldSTSegment == null) return;
        
        // Indikator warna klinis untuk deviasi segmen ST
        if (stValue >= 0.1) {
            jTextFieldSTSegment.setBackground(new java.awt.Color(255, 205, 205)); // Warna merah untuk Elevasi (STEMI)
            jTextFieldSTSegment.setForeground(new java.awt.Color(180, 0, 0));
            jTextFieldSTSegment.setToolTipText("ST Elevation (>= 0.1 mV / 1 mm): Potensi STEMI / Infark Miokard Akut!");
        } else if (stValue <= -0.1) {
            // ST Depression lebih dari 1 mm (kritis)
            jTextFieldSTSegment.setBackground(new java.awt.Color(255, 220, 180)); // Orange muda
            jTextFieldSTSegment.setForeground(new java.awt.Color(200, 80, 0));
            jTextFieldSTSegment.setToolTipText("ST Depression (> 1.0 mm / 0.1 mV): Potensi Iskemia Berat / NSTEMI!");
        } else if (stValue <= -0.05) {
            // ST Depression ringan (0.5 mm - 1.0 mm)
            jTextFieldSTSegment.setBackground(new java.awt.Color(215, 230, 255)); // Biru muda
            jTextFieldSTSegment.setForeground(new java.awt.Color(0, 75, 180));
            jTextFieldSTSegment.setToolTipText("ST Depression Mild (0.5 mm s/d 1.0 mm): Potensi Iskemia Ringan.");
        } else {
            jTextFieldSTSegment.setBackground(new java.awt.Color(138, 242, 175)); // Warna hijau untuk Normal
            jTextFieldSTSegment.setForeground(new java.awt.Color(50, 50, 50));
            jTextFieldSTSegment.setToolTipText("ST Amplitude Normal (-0.05 mV s/d 0.1 mV)");
        }
    }

    public void displayResults(ECGAnalyzer data) {
        this.isClassicAnalysis = true;
        if (btnHealthAdvice != null) {
            btnHealthAdvice.setVisible(false);
        }
        this.currentAnalyzer = data;
        
        java.text.DecimalFormat df  = new java.text.DecimalFormat("0.00");
        java.text.DecimalFormat df3 = new java.text.DecimalFormat("0.000");

        // Data Window & Fs
        jTextField1.setText(df.format(data.getDataWindow()));
        jTextField2.setText(String.valueOf((int) data.getFs()));
        
        // Peak Counts
        jTextField8.setText(String.valueOf(data.getRPeakCount()));
        jTextField9.setText(String.valueOf(data.getPPeakCount()));
        jTextField10.setText(String.valueOf(data.getTPeakCount()));
        
        // Heart Rate & RR (Konversi detik ke ms)
        jTextField3.setText(df.format(data.getHRAvg()));
        jTextField5.setText(df.format(data.getRRAvg()  * 1000));
        jTextField6.setText(df.format(data.getRRMin()  * 1000));
        jTextField7.setText(df.format(data.getRRMax()  * 1000));
        
        // Pengukuran Interval (Konversi detik ke ms)
        jTextField11.setText(df.format(data.getPRAvg()  * 1000));
        jTextField12.setText(df.format(data.getQRSAvg() * 1000));
        jTextField13.setText(df.format(data.getQTAvg()  * 1000));
        jTextField14.setText(df.format(data.getQTcAvg() * 1000));

        // Tampilkan formula QTc di label — single-line supaya tidak mengubah tinggi row GroupLayout
        String formula = data.getFormulaName();
        if (jLabel17 != null) {
            jLabel17.setText("QTc (" + formula + "): ");
        }

        // Segmen EKG (Konversi detik ke ms untuk interval/segment; amplitudo tetap mV)
        jTextFieldPR.setText(df.format(data.getPRSegmentAvg()  * 1000));
        jTextFieldSTInterval.setText(df.format(data.getSTIntervalAvg() * 1000));
        jTextFieldSTSegment.setText(df3.format(data.getSTSegmentAvg()));
        
        colorCodeSTSegment(data.getSTSegmentAvg());

        jtxtSDNN.setText(df.format(data.getHRVsdnn()));
        jtxtRMSSD.setText(df.format(data.getHRVrmssd()));
        jtxtNN50.setText(String.valueOf(data.getHRVnn50()));
        jtxtpNN50.setText(df.format(data.getHRVpnn50()));
        jtxtSD1.setText(df.format(data.getHRVsd1()));
        jtxtSD2.setText(df.format(data.getHRVsd2()));
    }
    
    public void setPatientInfo(String name, String id, String classification, double confidence, String riskLevel) {
        this.patientName = (name != null && !name.trim().isEmpty()) ? name : "N/A";
        this.patientID = (id != null && !id.trim().isEmpty()) ? id : "N/A";
        this.classificationResult = (classification != null && !classification.trim().isEmpty()) ? classification : "N/A";
        
        // Normalisasi confidence rate (0.0 - 1.0)
        if (confidence < 0) {
            this.confidenceRate = 0;
        } else if (confidence > 1) {
            this.confidenceRate = confidence > 100 ? 1.0 : confidence / 100.0;
        } else {
            this.confidenceRate = confidence;
        }
        
        this.riskLevel = (riskLevel != null && !riskLevel.trim().isEmpty()) ? riskLevel : "Unknown";
    }
    
    public void setPatientInfoComplete(String name, String id, String sex, String birthdate, 
                                       String ageStr,
                                       String classification, double confidence, String riskLevel) {
        setPatientInfo(name, id, classification, confidence, riskLevel);
        this.patientSex = (sex != null && !sex.trim().isEmpty()) ? sex : "N/A";
        this.patientBirthdate = (birthdate != null && !birthdate.trim().isEmpty()) ? birthdate : "N/A";
        
        // Parsing angka demografis pasien secara aman
        this.patientAge = parsePositiveInt(ageStr, 0, 150);
    }
    
    private int parsePositiveInt(String value, int min, int max) {
        if (value == null || value.trim().isEmpty()) return 0;
        try {
            int parsed = Integer.parseInt(value.trim());
            return (parsed >= min && parsed <= max) ? parsed : 0;
        } catch (NumberFormatException e) {
            try {
                double parsed = Double.parseDouble(value.trim());
                int intVal = (int) parsed;
                return (intVal >= min && intVal <= max) ? intVal : 0;
            } catch (NumberFormatException e2) {
                return 0;
            }
        }
    }
    
    public void setQwenAdvice(String interpretation, String action, String lifestyle, String disclaimer) {
        this.qwenInterpretation = (interpretation != null && !interpretation.isEmpty()) ? interpretation : "";
        this.qwenMedicalAction = (action != null && !action.isEmpty()) ? action : "";
        this.qwenLifestyle = (lifestyle != null && !lifestyle.isEmpty()) ? lifestyle : "";
        this.qwenDisclaimer = (disclaimer != null && !disclaimer.isEmpty()) ? disclaimer : "";
        this.hasQwenAdvice = !qwenInterpretation.isEmpty() || !qwenMedicalAction.isEmpty();
        
        logger.info("✓ Qwen advice stored. Has structured advice: " + hasQwenAdvice);
    }
    
    public void setPythonResults(int rPeaks, int pPeaks, int tPeaks, 
                                 int heartRate, double rrInterval,
                                 String classification, double confidence,
                                 double dataWindow, String formulaName,
                                 ECGAnalyzer analyzer) {
        this.isClassicAnalysis = false;
        this.heartRateAvg = heartRate;
        this.currentAnalyzer = analyzer;
        
        if (btnHealthAdvice != null) {
            btnHealthAdvice.setVisible(true);
        }
        java.text.DecimalFormat df = new java.text.DecimalFormat("0.00");
        
        // Data Window & Fs
        jTextField1.setText(df.format(dataWindow));
        jTextField2.setText("360");
        
        // Peak Counts
        jTextField8.setText(String.valueOf(rPeaks));
        jTextField9.setText(String.valueOf(pPeaks));
        jTextField10.setText(String.valueOf(tPeaks));
        
        // Heart Rate
        jTextField3.setText(df.format(heartRate));
        
        // RR Intervals (s -> ms)
        jTextField5.setText(df.format(rrInterval       * 1000));
        jTextField6.setText(df.format(rrInterval * 0.9 * 1000));
        jTextField7.setText(df.format(rrInterval * 1.1 * 1000));
        
        // Hasil Kalkulasi Interval & Segment (s -> ms)
        if (analyzer != null) {
            jTextField11.setText(df.format(analyzer.getPRAvg()  * 1000));
            jTextField12.setText(df.format(analyzer.getQRSAvg() * 1000));
            jTextField13.setText(df.format(analyzer.getQTAvg()  * 1000));
            jTextField14.setText(df.format(analyzer.getQTcAvg() * 1000));
            jTextFieldPR.setText(df.format(analyzer.getPRSegmentAvg()  * 1000));
            jTextFieldSTInterval.setText(df.format(analyzer.getSTIntervalAvg() * 1000));
            jTextFieldSTSegment.setText(new java.text.DecimalFormat("0.000").format(analyzer.getSTSegmentAvg()));
            
            colorCodeSTSegment(analyzer.getSTSegmentAvg());

            jtxtSDNN.setText(df.format(analyzer.getHRVsdnn()));
            jtxtRMSSD.setText(df.format(analyzer.getHRVrmssd()));
            jtxtNN50.setText(String.valueOf(analyzer.getHRVnn50()));
            jtxtpNN50.setText(df.format(analyzer.getHRVpnn50()));
            jtxtSD1.setText(df.format(analyzer.getHRVsd1()));
            jtxtSD2.setText(df.format(analyzer.getHRVsd2()));
        } else {
            jTextField11.setText(df.format(160.0));
            jTextField12.setText(df.format(100.0));
            jTextField13.setText(df.format(400.0));
            jTextField14.setText(df.format(410.0));
            jTextFieldPR.setText(df.format(80.0));
            jTextFieldSTInterval.setText(df.format(300.0));
            jTextFieldSTSegment.setText("0.000");
            
            colorCodeSTSegment(0.0);

            jtxtSDNN.setText("0.00");
            jtxtRMSSD.setText("0.00");
            jtxtNN50.setText("0");
            jtxtpNN50.setText("0.00");
            jtxtSD1.setText("0.00");
            jtxtSD2.setText("0.00");
        }
        
        // Tampilkan nama formula QTc — single-line supaya tidak mengubah tinggi row GroupLayout
        String shortName = "-";
        if (formulaName != null) {
            if (formulaName.contains("Bazett"))          shortName = "Bazett";
            else if (formulaName.contains("Fridericia"))  shortName = "Fridericia";
            else if (formulaName.contains("Framingham"))  shortName = "Framingham";
            else if (formulaName.contains("Hodges"))      shortName = "Hodges";
            else                                           shortName = formulaName;
        }
        if (jLabel17 != null) {
            jLabel17.setText("QTc (" + shortName + ") :");
        }
    }
    
    
    /**
     * Generate health advice based on ECG classification AND patient demographics
     * WHY: Provide clinical guidance using GenAI with complete clinical context
     * ENHANCED: Now includes patient physical data for more personalized advice
     */
    public String generateHealthAdvice() {
        // PRIORITY: Use Qwen-generated advice from Python backend if available
        if (hasQwenAdvice && !qwenInterpretation.isEmpty()) {
            return formatQwenAdvice();
        }
        
        // FALLBACK: Generate advice using local GeminiHealthAdvisor
        return generateLocalAdvice();
    }
    
    /**
     * Format Qwen-generated advice from Python backend
     */
    private String formatQwenAdvice() {
        StringBuilder report = new StringBuilder();
        report.append("─────────────────────────────────────────────────────────────────────\n");
        report.append("                                              ECG ANALYSIS REPORT                                                 \n");
        
        report.append("\n 📊 CLASSIFICATION RESULTS:\n");
        report.append("   Classification: ").append(classificationResult).append("\n");
        report.append("   Confidence: ").append(String.format("%.1f%%", confidenceRate * 100)).append("\n");
        report.append("   Risk Level: ").append(riskLevel).append("\n\n");
        
        report.append("📖 MEDICAL INTERPRETATION:\n");
        report.append("   ").append(qwenInterpretation).append("\n\n");
        
        report.append("🏥 RECOMMENDED MEDICAL ACTION:\n");
        report.append("   ").append(qwenMedicalAction).append("\n\n");
        
        report.append("🍎 LIFESTYLE RECOMMENDATIONS:\n");
        report.append("   ").append(qwenLifestyle).append("\n\n");
        
        report.append("─────────────────────────────────────────────────────────────────────\n");;
        report.append("                                                 ⚠  DISCLAIMER:                                                 \n");
        report.append("   ").append(qwenDisclaimer).append("\n");
        
        return report.toString();
    }
    
    /**
     * Generate local health advice using Gemini (fallback)
     */
    private String generateLocalAdvice() {
        // BMI calculation removed
        
        // Determine age-specific risk factors
        String ageRiskNote = "";
        if (patientAge > 0) {
            if (patientAge >= 65) {
                ageRiskNote = " Age-related cardiac monitoring recommended.";
            } else if (patientAge >= 45) {
                ageRiskNote = " Regular cardiovascular screening advised.";
            }
        }
        
        String kodeAsli = classificationResult; 
        if (kodeAsli != null) {
            kodeAsli = kodeAsli.trim();
        } else {
            kodeAsli = "Unknown";
        }
        
        // HITUNG ULANG TINGKAT RISIKO 
        String tingkatRisiko = projectecg.GeminiHealthAdvisor.calculateRiskLevel(kodeAsli);

        String konteksPasien = "Risk level: " + tingkatRisiko +
               ", Age: " + patientAge +
               ", Sex: " + patientSex;

        String advice = "";
        // Cek apakah parent adalah MainDashboard, jika iya gunakan saran dari jtxtNotes2
        if (this.getOwner() instanceof projectecg.MainDashboard) {
            projectecg.MainDashboard parent = (projectecg.MainDashboard) this.getOwner();
            String mainAdvice = parent.getHealthAdviceText();
            if (mainAdvice != null && !mainAdvice.trim().isEmpty() && !mainAdvice.contains("No health advice available")) {
                advice = mainAdvice;
                // Bersihkan disclaimer bawaan jtxtNotes2 ("⚠ Consult a cardiologist...") agar tidak double/duplikat
                int disclaimerIdx = advice.indexOf("\n\n⚠");
                if (disclaimerIdx != -1) {
                    advice = advice.substring(0, disclaimerIdx).trim();
                } else {
                    disclaimerIdx = advice.indexOf("⚠");
                    if (disclaimerIdx != -1) {
                        advice = advice.substring(0, disclaimerIdx).trim();
                    }
                }
            }
        }
        
        // Fallback jika tidak berhasil mengambil dari MainDashboard
        if (advice.isEmpty()) {
            // Use ADVANCED GeminiHealthAdvisor for AI-powered advice with risk level context
            advice = projectecg.GeminiHealthAdvisor.generateAdvancedHealthAdvice(
                kodeAsli,     
                confidenceRate,  
                konteksPasien   // <-- PENTING: Gunakan tingkatRisiko yang baru dihitung
            );
        }
        
        // Wrap in professional health report format with clear sections
        StringBuilder report = new StringBuilder();
        report.append("─────────────────────────────────────────────────────────────────────\n");
        report.append("                                                    ECG ANALYSIS REPORT                                             \n");
        
        report.append("\n📊 CLASSIFICATION RESULTS:\n");
        // Gunakan kodeAsli agar menampilkan "N", "V", atau "Other"
        report.append("   Classification: ").append(kodeAsli).append("\n"); 
        report.append("   Description: ").append(projectecg.GeminiHealthAdvisor.getClassificationDescription(kodeAsli)).append("\n");
        report.append("   Confidence: ").append(String.format("%.1f%%", confidenceRate * 100)).append("\n");
        // Gunakan tingkatRisiko agar tidak menampilkan "Unknown"
        report.append("   Risk Level: ").append(tingkatRisiko).append("\n\n");
        
        // NEW: Add patient-specific health context
        report.append("📋 PATIENT HEALTH CONTEXT:\n");
        if (patientAge > 0) {
            report.append("   Age Group: ").append(patientAge).append(" years");
            if (patientAge >= 65) report.append(" (Senior)");
            else if (patientAge >= 45) report.append(" (Middle-aged)");
            else if (patientAge >= 18) report.append(" (Adult)");
            else report.append(" (Young)");
            report.append("\n");
        }
        // BMI-specific advice removed
        
        report.append("\n💡 HEALTH ADVICE:\n");
        report.append("   ").append(advice).append("\n\n");
        
        report.append("─────────────────────────────────────────────────────────────────────\n");
        report.append("                                                                 ⚠  DISCLAIMER:                                                 \n");
        report.append("This advice is for informational purposes only and should not replace professional medical consultation.\n");
        report.append("Please consult with a healthcare professional for clinical decisions and treatment recommendations.\n");
        
        return report.toString();
    }
    
    /**
     * Generate patient demographics summary with professional formatting
     * WHY: Show complete patient context in health advice panel (readable format)
     */
    public String getPatientSummary() {
        StringBuilder summary = new StringBuilder();
        summary.append("─────────────────────────────────────────────────────────────────────\n");
        summary.append("                                                    PATIENT INFORMATION                                                 \n");
        
        summary.append("👤 PERSONAL DETAILS:\n");
        summary.append("   Name: ").append(patientName).append("\n");
        summary.append("   Patient ID: ").append(patientID).append("\n");
        summary.append("   Sex: ").append(patientSex).append("\n");
        
        if (!patientBirthdate.equals("N/A")) {
            summary.append("   Birthdate: ").append(patientBirthdate).append("\n");
        }
        
        return summary.toString();
    }
    
    private void applyFieldStyling() {
        javax.swing.JTextField[] allFields = {
            jTextField1, jTextField2, jTextField3, jTextField5,
            jTextField6, jTextField7, jTextField8, jTextField9, jTextField10,
            jTextField11, jTextField12, jTextField13, jTextField14,
            jTextFieldPR, jTextFieldSTInterval, jTextFieldSTSegment,
            jtxtSDNN, jtxtRMSSD, jtxtNN50, jtxtpNN50, jtxtSD1, jtxtSD2
        };

        java.awt.Color bgColor = java.awt.Color.WHITE;

        for (javax.swing.JTextField f : allFields) {
            if (f != null) {
                f.setEditable(false);
                f.setBackground(bgColor);
                f.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            }
        }
    }
}