/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projectecg;
import projectecg.services.PatientService;

/**
 *
 * @author fizel
 */
public class FindPatientPanel extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FindPatientPanel.class.getName());
    
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> rowSorter;
    /**
     * Creates new form FindPatientPanel
     */
    public FindPatientPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.getContentPane().setBackground(new java.awt.Color(242,242,242));

        // --- TAMBAHAN 2: Setup Sorter ---
        // 1. Ambil model
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPatients.getModel();
        
        // 2. Hapus baris kosong default (Solusi tahap sebelumnya)
        model.setRowCount(0);
        
        // 3. Pasang Sorter ke Tabel
        rowSorter = new javax.swing.table.TableRowSorter<>(model);
        tblPatients.setRowSorter(rowSorter);
        
        // 4. Default: Disable Tombol Delete & Pasang Listener Seleksi Baris
        btndelete.setEnabled(false);
        tblPatients.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // Tombol aktif jika ada baris yang dipilih
                    btndelete.setEnabled(tblPatients.getSelectedRow() != -1);
                }
            }
        });
        // --------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btnselect = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setForeground(new java.awt.Color(242, 242, 242));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pasien", "Nama", "Jenis Kelamin", "TTD", "Umur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatients.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblPatients);
        tblPatients.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel1.setText("Find Patient");

        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);

        btnnew.setText("New");
        btnnew.addActionListener(this::btnnewActionPerformed);

        btnselect.setText("Select");
        btnselect.addActionListener(this::btnselectActionPerformed);

        btnclose.setText("Close");
        btnclose.addActionListener(this::btncloseActionPerformed);

        btndelete.setText("Delete");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnnew))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnselect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnclose)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch)
                    .addComponent(btndelete)
                    .addComponent(btnnew))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnselect)
                    .addComponent(btnclose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Ambil Parent Frame (Jendela Utama)
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Ambil Model Tabel dari tblPatients
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPatients.getModel();

        // 3. Pinjam kunci database dari MainDashboard lalu buka NewPatientFrame
        if (parentFrame instanceof MainDashboard) {
            MainDashboard dashboard = (MainDashboard) parentFrame;
            
            // Perhatikan sekarang ada 4 isian, parameter terakhir mengambil service dari dashboard
            NewPatientFrame f = new NewPatientFrame(dashboard, true, model, dashboard.getPatientService());
            f.setLocationRelativeTo(null); 
            f.setVisible(true);
        }
    }                                      

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
    // Ambil teks dari kotak pencarian
        String text = txtsearch.getText();

        if (text.trim().length() == 0) {
            // Jika kosong, tampilkan semua data (hapus filter)
            rowSorter.setRowFilter(null);
        } else {
            // Jika ada teks, filter baris
            // "(?i)" artinya case-insensitive (huruf besar/kecil dianggap sama)
            // angka 1 di akhir artinya kita mencari di kolom "Name" (indeks 1)
            // Jika ingin mencari di semua kolom, hapus angka 1-nya.
            rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text, 1));}
               // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
    // 1. Cek apakah user sudah klik salah satu baris?
        int selectedRow = tblPatients.getSelectedRow();
        
        if (selectedRow != -1) {
            // 2. Konversi Index (PENTING KARENA ADA FITUR SEARCH/FILTER)
            // Jika user filter nama "Budi", dia visualnya di baris 0, 
            // tapi di data asli mungkin baris 50. Kita butuh index aslinya.
            int modelRow = tblPatients.convertRowIndexToModel(selectedRow);
            
            // 3. Ambil Model Tabel
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPatients.getModel();

            // 4. Ambil ID Pasien (Kolom 0)
            String id = model.getValueAt(modelRow, 0).toString();

            // 5. Kirim ke MainDashboard
            // Kita ambil induk jendela ini (Parent Window)
            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            
            // Pastikan induknya benar-benar MainDashboard
            if (parentWindow instanceof MainDashboard) {
                MainDashboard dashboard = (MainDashboard) parentWindow;
                
                // Panggil autoFillPatientData untuk mengambil data lengkap dari database
                try {
                    dashboard.autoFillPatientData(Integer.parseInt(id));
                } catch (Exception e) {
                    System.err.println("Error calling autoFillPatientData: " + e.getMessage());
                }
                
                // Tutup jendela pencarian
                this.dispose();
            }
        } else {
            // Jika user belum pilih baris tapi nekat klik Select
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih pasien terlebih dahulu!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnselectActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        // Konversi index visual ke index model (karena ada filter/sorting)
        int modelRow = tblPatients.convertRowIndexToModel(selectedRow);
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPatients.getModel();
        
        String idStr = model.getValueAt(modelRow, 0).toString();
        String name = model.getValueAt(modelRow, 1).toString();
        int patientId = Integer.parseInt(idStr);

        // Tampilkan konfirmasi dialog
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin menghapus data pasien: " + name + " (ID: " + idStr + ")?",
            "Konfirmasi Hapus Pasien",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Ambil Parent Frame
            java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (parentFrame instanceof MainDashboard) {
                MainDashboard dashboard = (MainDashboard) parentFrame;
                PatientService service = dashboard.getPatientService();
                
                // TODO: Proses hapus dari database MySQL
                if (service != null) {
                    boolean success = service.deletePatient(patientId);
                    if (success) {
                        model.removeRow(modelRow);
                        btndelete.setEnabled(false); // Reset status tombol
                        javax.swing.JOptionPane.showMessageDialog(this, "Data pasien berhasil dihapus.");
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data pasien dari database.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Koneksi database tidak tersedia.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    public javax.swing.table.DefaultTableModel getTableModel() {
        return (javax.swing.table.DefaultTableModel) tblPatients.getModel();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FindPatientPanel dialog = new FindPatientPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    public void populateTable(java.util.List<projectecg.models.Patient> patientList) {
        // Ambil model tabel
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);
        
        // Masukkan data satu per satu ke dalam baris tabel
        for (projectecg.models.Patient p : patientList) {
            String idStr = String.format("%03d", p.getId());
            model.addRow(new Object[]{
                idStr,
                p.getName(),
                p.getSex(),
                p.getBirthdate() != null ? p.getBirthdate().toString() : "-",
                p.getAge(),
                p.getWeight(),
                p.getHeight()
            });
        }
    }
}
