/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projectecg;

import projectecg.services.PatientService;
import java.util.logging.Level;

/**
 *
 * @author fizel
 */
public class NewPatientFrame extends javax.swing.JDialog {
    private javax.swing.table.DefaultTableModel tableModel;
    private PatientService patientService;  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewPatientFrame.class.getName());

    public NewPatientFrame(java.awt.Frame parent, boolean modal,
                          javax.swing.table.DefaultTableModel tableModel,
                          PatientService patientService) {  
        super(parent, modal);
        this.tableModel = tableModel;
        this.patientService = patientService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewPatientFrame = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtTTL = new javax.swing.JTextField();
        jtxtAge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtNIK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbGolDar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtxtPekerjaan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtKewarganegaraan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtStatusKawin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtAgama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NewPatientFrame.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Patient", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION), "Input Pasien", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel7.setText("Jenis Kelamin       : ");

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perempuan", "Laki-Laki" }));
        cmbSex.addActionListener(this::cmbSexActionPerformed);

        jLabel8.setText("Tempat/Tgl Lahir : ");

        jLabel9.setText("Status Perkawinan :");

        jtxtTTL.addActionListener(this::jtxtTTLActionPerformed);

        jtxtAge.addActionListener(this::jtxtAgeActionPerformed);

        jLabel12.setText("Nama                  :");

        txtname.addActionListener(this::txtnameActionPerformed);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        jLabel2.setText("NIK                      :");

        jLabel3.setText("Alamat                 :");

        jTextAreaAlamat.setColumns(20);
        jTextAreaAlamat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAlamat);

        jLabel5.setText("Gol. Darah :");

        cmbGolDar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A", "B", "AB", "O" }));

        jLabel6.setText("Pekerjaan               :");

        jLabel13.setText("Kewarganegaraan  :");

        jLabel14.setText("Umur                   :");

        jtxtStatusKawin.addActionListener(this::jtxtStatusKawinActionPerformed);

        jLabel15.setText("Agama                :");

        javax.swing.GroupLayout NewPatientFrameLayout = new javax.swing.GroupLayout(NewPatientFrame);
        NewPatientFrame.setLayout(NewPatientFrameLayout);
        NewPatientFrameLayout.setHorizontalGroup(
            NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPatientFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPatientFrameLayout.createSequentialGroup()
                        .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NewPatientFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewPatientFrameLayout.createSequentialGroup()
                                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewPatientFrameLayout.createSequentialGroup()
                                        .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewPatientFrameLayout.createSequentialGroup()
                                                .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbGolDar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtxtNIK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                            .addComponent(jtxtTTL)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewPatientFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewPatientFrameLayout.createSequentialGroup()
                                        .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(NewPatientFrameLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(106, 106, 106))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPatientFrameLayout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addComponent(jtxtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPatientFrameLayout.createSequentialGroup()
                        .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewPatientFrameLayout.createSequentialGroup()
                                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13))
                                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(NewPatientFrameLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtStatusKawin, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(NewPatientFrameLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtxtPekerjaan, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtKewarganegaraan)))))
                            .addGroup(NewPatientFrameLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        NewPatientFrameLayout.setVerticalGroup(
            NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPatientFrameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtTTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(cmbGolDar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewPatientFrameLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewPatientFrameLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtStatusKawin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtKewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(NewPatientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NewPatientFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NewPatientFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexActionPerformed

    private void jtxtTTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTTLActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    this.dispose(); 
    }//GEN-LAST:event_btnCancelActionPerformed


    private void jtxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAgeActionPerformed

    private void jtxtStatusKawinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStatusKawinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStatusKawinActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        String name = txtname.getText().trim();
        String sex = cmbSex.getSelectedItem().toString();
        String dobStr = jtxtTTL.getText().trim();
        int age = Integer.parseInt(jtxtAge.getText());
        double weight = 0.0;
        double height = 0.0;

        String nik = jtxtNIK.getText().trim();
        String alamat = jTextAreaAlamat.getText().trim();
        String golDarah = cmbGolDar.getSelectedItem().toString();
        String pekerjaan = jtxtPekerjaan.getText().trim();
        String kewarganegaraan = jtxtKewarganegaraan.getText().trim();
        String statusKawin = jtxtStatusKawin.getText().trim();
        String agama = jtxtAgama.getText().trim();

        if (name.isEmpty() || dobStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Nama dan Tanggal Lahir harus diisi!",
                "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        projectecg.models.Patient patient = new projectecg.models.Patient(name, sex, dobStr, age, weight, height);
        patient.setNik(nik);
        patient.setAlamat(alamat);
        patient.setGolDarah(golDarah);
        patient.setPekerjaan(pekerjaan);
        patient.setKewarganegaraan(kewarganegaraan);
        patient.setStatusKawin(statusKawin);
        patient.setAgama(agama);

        String tempatLahir = "";
        if (dobStr.contains(",")) {
            tempatLahir = dobStr.substring(0, dobStr.indexOf(",")).trim();
        }
        patient.setTempatLahir(tempatLahir);

        if (patientService != null) {
            int patientId = patientService.registerNewPatient(patient);
            if (patientId > 0) {
                String idStr = String.format("%03d", patientId);
                tableModel.addRow(new Object[]{idStr, name, sex, dobStr, age, weight, height});
                javax.swing.JOptionPane.showMessageDialog(this,
                    "✓ Patient saved successfully!\nPatient ID: " + patientId,
                    "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                logger.info("✓ Patient registered: " + name + " (ID: " + patientId + ")");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "✗ Failed to save patient to database",
                    "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "✗ Database service not available",
                "System Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (java.time.format.DateTimeParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Format tanggal salah! Gunakan format: dd/MM/yyyy",
            "Date Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Format Angka Salah!\nUmur harus bulat, Berat & Tinggi boleh desimal (pakai titik).",
            "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(), "Exception",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, "Error saving patient", e);
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NewPatientFrame dialog = new NewPatientFrame(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewPatientFrame;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbGolDar;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAlamat;
    private javax.swing.JTextField jtxtAgama;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtKewarganegaraan;
    private javax.swing.JTextField jtxtNIK;
    private javax.swing.JTextField jtxtPekerjaan;
    private javax.swing.JTextField jtxtStatusKawin;
    private javax.swing.JTextField jtxtTTL;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
