/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectecg;

/**
 *
 * @author April
 */
public class PatientHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientHistory.class.getName());
    private final projectecg.services.PatientService patientService;

    /**
     * Creates new form PatientHistory with a shared PatientService
     */
    public PatientHistory(projectecg.services.PatientService service) {
        initComponents();
        this.patientService = (service != null) ? service : new projectecg.services.PatientService();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        loadHistoryData();
        setColumnWidths();
        
        // Set ukuran awal window yang proporsional
        this.setSize(1000, 450);
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form PatientHistory
     */
    public PatientHistory() {
        this(null);
    }

    private void setColumnWidths() {
        if (jTable1.getColumnModel().getColumnCount() >= 9) {
            // Atur lebar preferred masing-masing kolom sesuai proporsi isi datanya
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(170); // Timestamp
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(130); // Nama Pasien
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(45);  // HR (Detak Jantung)
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(230); // Diagnosa Klasifikasi
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(85);  // Confidence Rate
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);  // ST Dev
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(65);  // QRS Dur
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(55);  // QTc
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(55);  // PR Int
        }
    }

    private String formatTimestamp(java.sql.Timestamp ts) {
        if (ts == null) {
            return "-";
        }
        // Format tanggal agar bersih tanpa mili-detik (.0) di bagian belakang
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        sdf.setTimeZone(java.util.TimeZone.getTimeZone("UTC")); // Set ke UTC agar sesuai dengan serverTimezone di .env
        return sdf.format(ts);
    }

    private void loadHistoryData() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear existing table data
        
        java.util.List<projectecg.models.Patient> patients = patientService.getAllPatients();
        
        // Urutkan data pasien berdasarkan tanggal analisis terbaru (Descending)
        patients.sort((p1, p2) -> {
            java.sql.Timestamp t1 = p1.getAnalysisDate();
            java.sql.Timestamp t2 = p2.getAnalysisDate();
            if (t1 == null && t2 == null) return 0;
            if (t1 == null) return 1;  // null ditaruh di paling bawah
            if (t2 == null) return -1;
            return t2.compareTo(t1);   // Terbaru ke terlama (descending)
        });
        
        for (projectecg.models.Patient p : patients) {
            if (p.hasAnalysisResults()) {
                model.addRow(new Object[]{
                    formatTimestamp(p.getAnalysisDate()), 
                    p.getName(),
                    p.getHeartRate(),
                    p.getArrhythmiaLabel(), // Returns description since we modified it to do so
                    String.format("%.2f%%", p.getConfidenceScore() * 100),
                    String.format("%.2f", p.getStDeviation()),
                    String.format("%.1f", p.getQrsDuration()),
                    String.format("%.1f", p.getQtcInterval()),
                    String.format("%.1f", p.getPrInterval())
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("History");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Timestamp", "Nama", "HR", "Diagnosa", "Confidence", "ST Dev", "QRS Dur", "QTc", "PR Int"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PatientHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
