/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectecg;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.fazecast.jSerialComm.SerialPort;
import com.fazecast.jSerialComm.SerialPortDataListener;
import com.fazecast.jSerialComm.SerialPortEvent;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

import projectecg.MainDashboard.SerialPortReader;
/**
 *
 * @author fizel
 */
public class MainDashboard extends javax.swing.JFrame {
    private BlockingQueue<Byte> queueByte = new LinkedBlockingQueue<>();
    private BlockingQueue<String> queueString = new LinkedBlockingQueue<>();
    private SerialCommBiner serialComm;
    private Thread parsingThread;
    private ThrdParsingECG parserRunnable;
    private javax.swing.Timer consumerTimer;

    private FindPatientPanel findPatientWindow;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    private String currentMode = "Monitoring"; 
    private Timer ecgTimer; 
    private int xGraph = 0; 
    private int[] lastY = new int[12]; 
    
    public String filterType = "-"; // Bandpass, Low-pass, High-pass
    public boolean isNotchOn = false;
    public boolean isEmgOn = false;
    public int notchFreq = 50;
    public String qtcFormula = "-";
    // 50 atau 60 Hz
    // --- VARIABLES FOR WAVE VISUALIZATION ---
    public boolean showPWave = false;
    public boolean showTWave = false;
    public boolean showRWave = false;
    
    // Penampung lokasi index hasil analisis background
    private java.util.List<Integer> cachedPIndices = new java.util.ArrayList<>();
    private java.util.List<Integer> cachedTIndices = new java.util.ArrayList<>();
    private java.util.List<Integer> cachedRIndices = new java.util.ArrayList<>();
    
    private java.util.List<double[]> leadsData = new java.util.ArrayList<>();
    private java.util.List<double[]> processedData = new java.util.ArrayList<>();// Menampung data dari file
    private int currentDataIndex = 0;         // Pointer untuk animasi (sedang baca data ke berapa)
    private boolean isFileLoaded = false;     // Penanda apakah user sudah upload file
    
    
    private SerialPort serialPort; 
    private String serialBuffer = ""; // Untuk menampung potongan data string
    private int writeIndex = 0;       // Posisi index data saat merekam real-time
    private final int MAX_SAMPLE = 50000; // Kapasitas rekam (misal cukup utk bbrp menit)
    private int currentSpeedStep = 2;
    
    private double currentGainMultiplier = 1.0;
    private int layoutRows = 12; // Default 1x12 (12 Baris)
    private int layoutCols = 1;  // Default 1x12 (1 Kolom)
    
    private double currentFs = 125.0;
    private int refreshCounter = 0;
    public int rhythmTimeSeconds = 10;
    
    
    public MainDashboard() {
        initComponents();
        findPatientWindow = new FindPatientPanel(this, true);
        findPatientWindow.setLocationRelativeTo(this);
    
        // --- TAMBAHAN LOGIKA AWAL ---
        // 1. Matikan tombol Analyze di awal (karena default Monitoring)
        btnAnalyze.setEnabled(false); 
        
        // 2. Setup Timer untuk Animasi Grafik (Jalan setiap 50 milidetik)
        ecgTimer = new Timer(50, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                drawLiveECG(); // Method menggambar (kita buat di poin C)
            }
        });
        ecgTimer.start(); // Jalankan animasi // Warna putih agar kontras di background hitam/abu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jlblStatus = new javax.swing.JTextField();
        jlblHR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_port = new javax.swing.JComboBox<>();
        jrecord = new javax.swing.JToggleButton();
        btnAnalyze = new javax.swing.JButton();
        btnsettings = new javax.swing.JButton();
        jPanel_ecgsignal = new javax.swing.JPanel();
        jbtnfreeze = new javax.swing.JButton();
        jbtnDownload = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_cbSpeed = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBox_cbGain = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jon = new javax.swing.JToggleButton();
        jPanel_panelpatient2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtxtBirthdate2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtNotes2 = new javax.swing.JTextArea();
        jtxtAge2 = new javax.swing.JTextField();
        jtxtWeight2 = new javax.swing.JTextField();
        jtxtHeight2 = new javax.swing.JTextField();
        txtsex = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jupload = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DASHBOARD ECG");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("ID :");

        jtxtID.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jtxtID.addActionListener(this::jtxtIDActionPerformed);

        jLabel6.setText("STATUS  :");

        jlblStatus.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlblStatus.addActionListener(this::jlblStatusActionPerformed);

        jlblHR.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jlblHR.setText("--");
        jlblHR.addActionListener(this::jlblHRActionPerformed);

        jLabel3.setText("HR:");

        jLabel4.setText("♥");

        jLabel5.setText("PORT:");

        jComboBox_port.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM4", "COM5", "COM6", "COM10", "COM12" }));

        jrecord.setText("Record/Stop");
        jrecord.addActionListener(this::jrecordActionPerformed);

        btnAnalyze.setText("Analyze");
        btnAnalyze.addActionListener(this::btnAnalyzeActionPerformed);

        btnsettings.setText("Settings");
        btnsettings.addActionListener(this::btnsettingsActionPerformed);

        jPanel_ecgsignal.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_ecgsignal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel_ecgsignalLayout = new javax.swing.GroupLayout(jPanel_ecgsignal);
        jPanel_ecgsignal.setLayout(jPanel_ecgsignalLayout);
        jPanel_ecgsignalLayout.setHorizontalGroup(
            jPanel_ecgsignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_ecgsignalLayout.setVerticalGroup(
            jPanel_ecgsignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jbtnfreeze.setText("Freeze");
        jbtnfreeze.addActionListener(this::jbtnfreezeActionPerformed);

        jbtnDownload.setText("Download");
        jbtnDownload.addActionListener(this::jbtnDownloadActionPerformed);

        jLabel13.setText("Speed:");

        jComboBox_cbSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25mm/s", "12.5 mm/s", "50 mm/s" }));
        jComboBox_cbSpeed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox_cbSpeed.addActionListener(this::jComboBox_cbSpeedActionPerformed);

        jLabel14.setText("Gain:");

        jComboBox_cbGain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 mm/mV", "10 mm/mV", "20 mm/mV" }));
        jComboBox_cbGain.addActionListener(this::jComboBox_cbGainActionPerformed);

        jLabel17.setText("Grid:");

        jon.setBackground(new java.awt.Color(50, 50, 50));
        jon.setText("✓");
        jon.setToolTipText("");
        jon.addActionListener(this::jonActionPerformed);

        jPanel_panelpatient2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Patient Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel_panelpatient2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel23.setText("Sex                : ");

        jLabel24.setText("Birthdate       : ");

        jLabel25.setText("Age (year)     : ");

        jLabel26.setText("Weight (kg)   : ");

        jLabel27.setText("Height (cm)   : ");

        jLabel28.setText("Health Advice : ");

        jtxtBirthdate2.addActionListener(this::jtxtBirthdate2ActionPerformed);

        jtxtNotes2.setColumns(20);
        jtxtNotes2.setRows(5);
        jScrollPane4.setViewportView(jtxtNotes2);

        jtxtAge2.addActionListener(this::jtxtAge2ActionPerformed);

        jtxtWeight2.addActionListener(this::jtxtWeight2ActionPerformed);

        jtxtHeight2.addActionListener(this::jtxtHeight2ActionPerformed);

        txtsex.addActionListener(this::txtsexActionPerformed);

        jLabel29.setText("Name            :");

        txtname.addActionListener(this::txtnameActionPerformed);

        javax.swing.GroupLayout jPanel_panelpatient2Layout = new javax.swing.GroupLayout(jPanel_panelpatient2);
        jPanel_panelpatient2.setLayout(jPanel_panelpatient2Layout);
        jPanel_panelpatient2Layout.setHorizontalGroup(
            jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_panelpatient2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtWeight2)
                    .addComponent(jtxtHeight2)
                    .addComponent(jtxtBirthdate2)
                    .addComponent(jtxtAge2)
                    .addComponent(txtsex))
                .addContainerGap())
            .addGroup(jPanel_panelpatient2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane4)
                .addGap(6, 6, 6))
            .addGroup(jPanel_panelpatient2Layout.createSequentialGroup()
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_panelpatient2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel28))
                    .addGroup(jPanel_panelpatient2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_panelpatient2Layout.setVerticalGroup(
            jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_panelpatient2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jtxtBirthdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jtxtAge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jtxtWeight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_panelpatient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jtxtHeight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFind.setText("Find");
        btnFind.addActionListener(this::btnFindActionPerformed);

        btnNew.setText("New");
        btnNew.addActionListener(this::btnNewActionPerformed);

        jupload.setText("Upload csv");
        jupload.addActionListener(this::juploadActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 x 12", "2 x  6", "3 x 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_cbSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_cbGain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jupload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnfreeze, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel_panelpatient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlblHR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_port, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(btnAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsettings, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel_ecgsignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jlblHR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_panelpatient2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsettings)
                            .addComponent(btnAnalyze)
                            .addComponent(jrecord)
                            .addComponent(jComboBox_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_ecgsignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jComboBox_cbSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_cbGain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnfreeze)
                        .addComponent(jbtnDownload)
                        .addComponent(jupload)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        jPanel_ecgsignal.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDActionPerformed

    private void jlblStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblStatusActionPerformed

    private void jlblHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblHRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblHRActionPerformed

    private void btnAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-btnAnalyzeActionPerformed
    // ════════════════════════════════════════════════════════════════════════════════════════════
    // NAVIGATION: btnAnalyze → Triggers Python Analysis directly (REFACTORED)
    // PURPOSE: Runs Python ML Model Classification and shows Health Report immediately
    // FLOW: Click Analyze → Python Analysis → Health Report Dialog → OK → Detailed Metrics Panel
    // ════════════════════════════════════════════════════════════════════════════════════════════
    
    // 1. VALIDATE: Check if ECG data is loaded
        if (!isFileLoaded || leadsData == null || leadsData.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please upload CSV file first!");
            return;
        }

        // 2. DIRECT EXECUTION: Run Python analysis immediately (NO choice dialog)
        analyzewithPython();
    }//GEN-LAST:event-btnAnalyzeActionPerformed

    private void btnsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-btnsettingsActionPerformed
        // Navigation: Open Settings Dialog
        // WHY: .setEnabled() is used to disable ECG settings when in Monitoring mode
        // This prevents the user from changing filters when just viewing live data
        Settings settingsWindow = new Settings(this, true);
        
        // Pass current settings to the dialog so user sees their previous choices
        settingsWindow.setCurrentSelection(
                this.currentMode, 
                this.filterType, 
                this.isNotchOn,
                this.notchFreq,
                this.isEmgOn,
                this.qtcFormula,
                this.rhythmTimeSeconds,
                this.showPWave, 
                this.showTWave, 
                this.showRWave  
        );
        
        // Display the Settings window
        settingsWindow.setLocationRelativeTo(this);
        settingsWindow.setVisible(true);
        
        // NEW: After settings dialog closes, enforce button state based on current mode
        enforceButtonState();
    }//GEN-LAST:event-btnsettingsActionPerformed

    private void jbtnfreezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jbtnfreezeActionPerformed
        // Cek apakah Timer sedang jalan atau mati
        if (ecgTimer.isRunning()) {
            // JIKA SEDANG JALAN -> MATIKAN (FREEZE)
            ecgTimer.stop();
            jbtnfreeze.setText("Resume"); // Ubah teks tombol jadi Resume
            jbtnfreeze.setBackground(Color.GREEN); // Opsional: Beri warna merah biar jelas
        } else {
            // JIKA SEDANG MATI -> JALANKAN LAGI (RESUME)
            ecgTimer.start();
            jbtnfreeze.setText("Freeze"); // Kembalikan teks jadi Freeze
            jbtnfreeze.setBackground(null); // Kembalikan warna asli
        }        // TODO add your handling code here:
    }//GEN-LAST:event-jbtnfreezeActionPerformed

    private void jbtnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jbtnDownloadActionPerformed
        // ════════════════════════════════════════════════════════════════════════════════════════════
        // DOWNLOAD ECG SIGNAL: Export recorded/uploaded ECG data to CSV file
        // PURPOSE: Allows user to save 12-lead ECG data for external analysis or archiving
        // SUPPORTS: Both real-time recorded data and uploaded CSV file data
        // ════════════════════════════════════════════════════════════════════════════════════════════
        
        // 1. VALIDATE: Check if ECG data exists
        if (leadsData == null || leadsData.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No ECG data to download!\n\nPlease either:\n• Upload a CSV file, or\n• Record data from serial port first.",
                "No Data Available", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if data has actual samples
        int sampleCount = leadsData.get(0).length;
        if (sampleCount == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "ECG data is empty. Please record or upload data first.",
                "Empty Data", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. ASK USER: Export raw, processed, or both?
        String[] options = {"Raw Signal", "Filtered Signal", "Both Files", "Cancel"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this,
            "Which data would you like to export?\n\n" +
            "• Raw Signal: Original unfiltered ECG data\n" +
            "• Filtered Signal: Data with applied filters (Bandpass, Notch, etc.)\n" +
            "• Both Files: Export both raw and filtered as separate files",
            "Select Export Type",
            javax.swing.JOptionPane.DEFAULT_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        
        if (choice == 3 || choice == javax.swing.JOptionPane.CLOSED_OPTION) {
            return; // User cancelled
        }
        
        // choice: 0 = Raw, 1 = Filtered, 2 = Both
        
        // 3. FILE CHOOSER: Let user select save location
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save ECG Data as CSV");
        
        // Generate default filename with patient ID and timestamp
        String patientID = jtxtID.getText().trim();
        String timestamp = new java.text.SimpleDateFormat("yyyyMMdd_HHmmss").format(new java.util.Date());
        String baseFilename = "ECG_" + (patientID.isEmpty() ? "Unknown" : patientID) + "_" + timestamp;
        
        // For "Both" option, use base name without suffix
        String defaultFilename = (choice == 2) ? baseFilename + "_raw.csv" : baseFilename + ".csv";
        fileChooser.setSelectedFile(new File(defaultFilename));
        
        // Set file filter to CSV
        FileNameExtensionFilter csvFilter = new FileNameExtensionFilter("CSV Files (*.csv)", "csv");
        fileChooser.setFileFilter(csvFilter);
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return; // User cancelled file dialog
        }
        
        // 4. GET FILE PATH: Ensure .csv extension
        File fileToSave = fileChooser.getSelectedFile();
        String filePath = fileToSave.getAbsolutePath();
        if (filePath.toLowerCase().endsWith(".csv")) {
            filePath = filePath.substring(0, filePath.length() - 4); // Remove .csv for base path
        }
        
        String patientName = txtname.getText().trim();
        boolean success = false;
        String resultMessage = "";
        
        // 5. EXPORT BASED ON CHOICE
        if (choice == 2) {
            // === BOTH FILES: Export raw and filtered separately ===
            File rawFile = new File(filePath + "_raw.csv");
            File filteredFile = new File(filePath + "_filtered.csv");
            
            // Check overwrite for both files
            if (rawFile.exists() || filteredFile.exists()) {
                int overwrite = javax.swing.JOptionPane.showConfirmDialog(this,
                    "One or both files already exist. Overwrite?",
                    "Confirm Overwrite",
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if (overwrite != javax.swing.JOptionPane.YES_OPTION) {
                    return;
                }
            }

           


            // Export Raw Signal
            boolean rawSuccess = CSVExporter.exportSignalToCSV(
                rawFile, leadsData, currentFs, patientID, patientName);
            
            // Export Filtered Signal
            boolean filteredSuccess = CSVExporter.exportSignalToCSV(
                filteredFile, processedData, currentFs, patientID, patientName);
            
            success = rawSuccess && filteredSuccess;
            
            if (success) {
                resultMessage = "Both ECG files exported successfully!\n\n" +
                    "Raw File: " + rawFile.getName() + "\n" +
                    "Filtered File: " + filteredFile.getName() + "\n" +
                    "Location: " + rawFile.getParent() + "\n" +
                    "Samples: " + sampleCount + "\n" +
                    "Duration: " + String.format("%.2f", sampleCount / currentFs) + " seconds";
            } else {
                resultMessage = "Export partially failed.\n" +
                    "Raw: " + (rawSuccess ? "Success" : "Failed") + "\n" +
                    "Filtered: " + (filteredSuccess ? "Success" : "Failed");
            }
        } else {
            // === SINGLE FILE: Export raw OR filtered ===
            fileToSave = new File(filePath + ".csv");
            
            // Confirm overwrite if file exists
            if (fileToSave.exists()) {
                int overwrite = javax.swing.JOptionPane.showConfirmDialog(this,
                    "File already exists. Overwrite?",
                    "Confirm Overwrite",
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if (overwrite != javax.swing.JOptionPane.YES_OPTION) {
                    return;
                }
            }
            
            boolean exportProcessed = (choice == 1); // 0 = Raw, 1 = Filtered
            java.util.List<double[]> dataToExport = exportProcessed ? processedData : leadsData;
            
            success = CSVExporter.exportSignalToCSV(
                fileToSave, dataToExport, currentFs, patientID, patientName);
            
            String dataType = exportProcessed ? "Filtered" : "Raw";
            resultMessage = "ECG data exported successfully!\n\n" +
                "File: " + fileToSave.getAbsolutePath() + "\n" +
                "Type: " + dataType + " Signal\n" +
                "Samples: " + sampleCount + "\n" +
                "Duration: " + String.format("%.2f", sampleCount / currentFs) + " seconds";
        }
        
        // 6. SHOW RESULT: Success or failure message
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this,
                resultMessage,
                "Export Successful",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Failed to export ECG data.\nPlease check file permissions and try again.",
                "Export Failed",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event-jbtnDownloadActionPerformed

    private void jComboBox_cbSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jComboBox_cbSpeedActionPerformed
    // Ambil teks yang dipilih user (misal: "50 mm/s")
    String selected = jComboBox_cbSpeed.getSelectedItem().toString();
    
    // Atur langkah piksel (speed) berdasarkan teks
    if (selected.contains("12.5")) {
        currentSpeedStep = 1; // Lambat (Rapat)
    } else if (selected.contains("50")) {
        currentSpeedStep = 4; // Cepat (Lebar/Zoom)
    } else {
        currentSpeedStep = 2; // Normal (25mm/s)
    }
    
    // Opsional: Reset layar agar grafik tidak menumpuk/berantakan saat ganti speed
    resetBackground();        // TODO add your handling code here:
    }//GEN-LAST:event-jComboBox_cbSpeedActionPerformed

    private void jonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jonActionPerformed
    // Tombol ini ToggleButton.
        // Jika ON -> jon.isSelected() bernilai true
        // Jika OFF -> jon.isSelected() bernilai false
        
        // Kita ubah teks tombol biar informatif
        if (jon.isSelected()) {
            jon.setText("✓");
        } else {
            jon.setText("x");
        }
        resetBackground();
        // Fokus akan dikerjakan di method drawLiveECG
    }//GEN-LAST:event-jonActionPerformed

    private void jtxtBirthdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jtxtBirthdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event-jtxtBirthdate2ActionPerformed

    private void jtxtAge2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jtxtAge2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event-jtxtAge2ActionPerformed

    private void jtxtWeight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jtxtWeight2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event-jtxtWeight2ActionPerformed

    private void jtxtHeight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jtxtHeight2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event-jtxtHeight2ActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-btnFindActionPerformed
        // Navigation: Open FindPatientPanel
        // WHY: This opens a dialog to search for existing patients in the database
        findPatientWindow.setLocationRelativeTo(this);
        findPatientWindow.setVisible(true);
    }//GEN-LAST:event-btnFindActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-btnNewActionPerformed
        // Navigation: Open NewPatientFrame
        // WHY: This allows the user to register a new patient and add them to the table
        // The table model is passed so new patients can be added to the database view
        javax.swing.table.DefaultTableModel model = findPatientWindow.getTableModel();
        NewPatientFrame newPatient = new NewPatientFrame(this, true, model);
        newPatient.setLocationRelativeTo(this);
        newPatient.setVisible(true);
    }//GEN-LAST:event-btnNewActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event-txtnameActionPerformed

    private void juploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-juploadActionPerformed
    // ═══════════════════════════════════════════════════════════════════════════════════════════════════════════
    // STATE MANAGEMENT: Upload CSV → Enable Analyze Button
    // RULE 1: Analyze button starts DISABLED (set in constructor)
    // RULE 2: After successful CSV upload, Analyze becomes ENABLED
    // RULE 3: Works in BOTH modes - Diagnose Mode (Import CSV) and Monitoring Mode (Real-time Recording)
    // ═══════════════════════════════════════════════════════════════════════════════════════════════════════════
    
    JFileChooser chooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV Files", "csv");
    chooser.setFileFilter(filter);

    int returnVal = chooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            
            // Variabel sementara untuk menampung data per kolom
            // List didalam List (Baris -> Kolom)
            ArrayList<ArrayList<Double>> tempColumns = new ArrayList<>();

            // Baca Header untuk tahu ada berapa kolom
            String header = br.readLine();
            if (header != null) {
                String[] cols = header.split(",");
                // Siapkan arraylist untuk setiap kolom data (mulai index 1 karena index 0 biasanya timestamp)
                for (int i = 1; i < cols.length; i++) {
                    tempColumns.add(new ArrayList<>());
                }
            }

            // Baca Isi Data
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                
                // Loop setiap kolom mulai dari index 1 (asumsi index 0 adalah waktu)
                for (int i = 1; i < values.length; i++) {
                    // Pastikan kolom tersedia di tempColumns
                    if ((i - 1) < tempColumns.size()) {
                        try {
                            double val = Double.parseDouble(values[i]);
                            tempColumns.get(i - 1).add(val);
                        } catch (NumberFormatException e) {
                            tempColumns.get(i - 1).add(0.0); // Default jika error parsing
                        }
                    }
                }
            }
            br.close();

            // KONVERSI KE STRUKTUR UTAMA (leadsData)
            leadsData.clear(); // Bersihkan data lama
            for (ArrayList<Double> colData : tempColumns) {
                double[] primitiveArr = new double[colData.size()];
                for (int i = 0; i < colData.size(); i++) {
                    primitiveArr[i] = colData.get(i);
                }
                leadsData.add(primitiveArr);
            }

           // === START REVISI TOTAL (GANTIKAN KODE LAMA DENGAN INI) ===
            
            // 1. Reset Status & Pointer Data
            isFileLoaded = true;
            currentDataIndex = 0; // Mulai baca CSV dari baris pertama
            xGraph = 0;           // Mulai gambar dari sisi kiri panel

            // 2. Reset Baseline Grafik
            // Mencegah garis melompat/melintang saat transisi data
            int h = jPanel_ecgsignal.getHeight();
            for (int i = 0; i < 12; i++) {
                lastY[i] = h / 2; // Set posisi awal garis di tengah-tengah baris
            }

            // 3. Hard Reset Tampilan (Solusi Anti-Lag/Bayangan)
            resetBackground();         // Menghapus coretan hijau data lama
            jPanel_ecgsignal.repaint(); // Menggambar ulang grid bersih secara instan

            // 4. Update UI & Informasi File
            jlblStatus.setText("FILE LOADED: " + file.getName() + " (" + leadsData.size() + " Leads)");
            btnAnalyze.setToolTipText("Click to run Model Classification");

            // 5. Jalankan Engine Analisis Background
            recalculateFilters(); // Hitung filter digital sesuai setting
            updateWaveMarkers();  // Cari P, Q, R, S, T untuk visualisasi
            enforceButtonState(); // Tentukan tombol Analyze nyala/mati sesuai mode
            updateAutoHR();       // Hitung Heart Rate awal

            // === END REVISI TOTAL ===
        } catch (Exception e) {
            System.out.println("Error reading CSV: " + e.getMessage());
            e.printStackTrace();
            jlblStatus.setText("ERROR LOADING FILE");
        }
    }
    }//GEN-LAST:event-juploadActionPerformed

    private void jrecordActionPerformed(java.awt.event.ActionEvent evt) {
        Object selectedItem = jComboBox_port.getSelectedItem();
        if (selectedItem == null) return;
        String portName = selectedItem.toString();

        if (jrecord.isSelected()) {
            // === START RECORDING ===
            try {
                // 1. Clear Queues & Data
                queueByte.clear();
                queueString.clear();
                leadsData.clear();
                processedData.clear();
                for(int i=0; i<12; i++) {
                leadsData.add(new double[MAX_SAMPLE]);
                processedData.add(new double[MAX_SAMPLE]);
                }
                writeIndex = 0;
                currentDataIndex = 0;

                // 2. Init & Open Serial Comm (The Ear)
                // 115200 is standard for this specific DAQ firmware usually
                serialComm = new SerialCommBiner(portName, 115200, queueByte); 
                serialComm.openPortEvent(); // Starts listening to bytes

                if (serialComm.isOpen()) {
                    // 3. Init & Start Parser (The Brain)
                    parserRunnable = new ThrdParsingECG(this, queueByte, queueString);
                    parsingThread = new Thread(parserRunnable);
                    parsingThread.start();

                    // 4. Start Consumer Timer (To update Dashboard from Queue)
                    // Reads from queueString every 10ms
                    consumerTimer = new javax.swing.Timer(10, e -> processParsedData());
                    consumerTimer.start();

                    jlblStatus.setText("Connected: " + portName);
                    jrecord.setText("STOP");
                    btnAnalyze.setEnabled(false);
                    isFileLoaded = true;
                } else {
                    jrecord.setSelected(false);
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to open port.");
                }
            } catch (Exception e) {
                e.printStackTrace();
                jrecord.setSelected(false);
            }

        } else {
            // === STOP RECORDING ===
            // 1. Stop Serial
            try {
                if (serialComm != null) serialComm.closePort();
            } catch (Exception e) {}
            
            // 2. Stop Parser
            if (parserRunnable != null) parserRunnable.setExit();
            
            // 3. Stop Consumer Timer
            if (consumerTimer != null) consumerTimer.stop();

            jrecord.setText("Record");
            jlblStatus.setText("Recording Stopped.");
            trimArrays(); 
            enforceButtonState();
        }
    }//GEN-LAST:event-jrecordActionPerformed

    private void txtsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-txtsexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event-txtsexActionPerformed

    private void jComboBox_cbGainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jComboBox_cbGainActionPerformed
    // Ambil teks yang dipilih user
    String selected = jComboBox_cbGain.getSelectedItem().toString();
    
    // Tentukan pengali berdasarkan pilihan
    if (selected.contains("5 mm/mV")) {
        currentGainMultiplier = 0.5; // Perkecil setengah
    } else if (selected.contains("20 mm/mV")) {
        currentGainMultiplier = 2.0; // Perbesar dua kali
    } else {
        currentGainMultiplier = 1.0; // Normal (10 mm/mV)
    }
    
    // Opsional: Bersihkan layar agar perubahan langsung terasa bersih
    resetBackground();      // TODO add your handling code here:
    }//GEN-LAST:event-jComboBox_cbGainActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event-jComboBox1ActionPerformed
    String selected = jComboBox1.getSelectedItem().toString();
        
        // Atur baris dan kolom berdasarkan pilihan
        if (selected.contains("2 x")) { 
            // Layout 2 x 6 (2 Kolom, 6 Baris per kolom)
            layoutCols = 2;
            layoutRows = 6;
        } else if (selected.contains("3 x")) {
            // Layout 3 x 4 (3 Kolom, 4 Baris per kolom)
            layoutCols = 3;
            layoutRows = 4;
        } else {
            // Default 1 x 12
            layoutCols = 1;
            layoutRows = 12;
        }
        
        // Reset grafik agar layout baru tergambar bersih
        resetBackground();
        xGraph = 0; // Kembalikan pointer ke awal
    }//GEN-LAST:event-jComboBox1ActionPerformed
   
// Letakkan di MainDashboard.java paling bawah (sebelum tutup kurung class)
    public void loadPatientData(String id, String name, String sex, String dob, String age, String weight, String height) {
        // Parameter di atas harus 7 biji, semuanya String.
        
        jtxtID.setText(id);
        txtname.setText(name); // Pastikan variable textfield nama kamu di GUI bernama 'txtname'
        txtsex.setText(sex);          
        jtxtBirthdate2.setText(dob);
        jtxtAge2.setText(age);
        jtxtWeight2.setText(weight);
        jtxtHeight2.setText(height);
        
        
    }
    
    // ════════════════════════════════════════════════════════════════════════════════════════════
    // PUBLIC SETTER: Allows external classes to update the Health Advice text area
    // PURPOSE: Data Sync - analyzepanel and other classes can push health advice to MainDashboard
    // USAGE: mainDashboard.updateHealthAdviceBox(adviceString);
    // ════════════════════════════════════════════════════════════════════════════════════════════
    /**
     * Updates the Health Advice text box on the main dashboard.
     * This method allows other classes (like analyzepanel) to send health advice
     * to be displayed in the patient information panel.
     * 
     * @param advice The health advice text to display
     */
    public void updateHealthAdviceBox(String advice) {
        if (advice == null || advice.trim().isEmpty()) {
            jtxtNotes2.setText("No health advice available.");
        } else {
            jtxtNotes2.setText(advice);
        }
        jtxtNotes2.setCaretPosition(0); // Scroll to top
    }
    
    // --- METHOD 1: MENERIMA SETTING DARI PANEL SETTINGS ---
    public void setAppMode(String mode) {
           this.currentMode = mode;
    xGraph = 0; // Reset X

    // Reset Layar
    Graphics g = jPanel_ecgsignal.getGraphics();
    if (g != null) {
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, jPanel_ecgsignal.getWidth(), jPanel_ecgsignal.getHeight());
        // (Kode gambar grid tetap sama seperti punya kamu...)
        if (jon.isSelected()) {
             g.setColor(new Color(50, 50, 50));
             for (int i = 0; i < jPanel_ecgsignal.getWidth(); i += 50) g.drawLine(i, 0, i, jPanel_ecgsignal.getHeight());
             for (int i = 0; i < jPanel_ecgsignal.getHeight(); i += 50) g.drawLine(0, i, jPanel_ecgsignal.getWidth(), i);
        }
    }

    int h = jPanel_ecgsignal.getHeight();

    if ("Monitoring".equals(mode)) {
        // --- MODE MONITORING: TAMPILKAN 12 BARIS (RAW DATA) ---
        // WHY: Monitoring mode shows all 12 leads without any filtering/analysis
        int rows = 12; // Show all 12 leads
        int gap = h / rows;
        for (int i = 0; i < rows; i++) {
            lastY[i] = (i * gap) + (gap / 2);
        }

        // UI LOGIC FOR MONITORING MODE:
        // CRITICAL: ALWAYS disable Analyze in Monitoring mode
        btnAnalyze.setEnabled(false);
        btnAnalyze.setToolTipText("Switch to Classification Mode to enable analysis");
        jrecord.setVisible(true);        // Show record button to capture real-time data
        jrecord.setText("Record");       // Reset button text
        jComboBox1.setEnabled(true);     // Allow layout selection
        jlblStatus.setText("MONITORING - 12 Leads");

    } else {
        // --- MODE SIGNAL CLASSIFICATION: TAMPILKAN 1 BARIS (LEAD II) ---
        // WHY: Classification mode focuses on single lead with ML analysis
        lastY[0] = h / 2;
        
        // UI LOGIC FOR SIGNAL CLASSIFICATION MODE:
        // Enable Analyze ONLY if data is already loaded
        if (isFileLoaded) {
            btnAnalyze.setEnabled(true);
            btnAnalyze.setToolTipText("Click to run Model Classification");
        } else {
            btnAnalyze.setEnabled(false);
            btnAnalyze.setToolTipText("Upload CSV or record data first");
        }
        
        jrecord.setVisible(true);             // Show record button to load CSV or capture data
        jComboBox1.setEnabled(false);         // Disable layout (fixed to 1 lead)
        jlblStatus.setText("CLASSIFICATION - Analysis");
    }
    }

    // --- METHOD 2: MENGGAMBAR GRAFIK (VISUALISASI) ---
    // --- GANTI SELURUH METHOD drawLiveECG DENGAN INI ---
          private void drawLiveECG() {
    Graphics g = jPanel_ecgsignal.getGraphics();
    if (g == null) return;
    Graphics2D g2 = (Graphics2D) g;

    int totalW = jPanel_ecgsignal.getWidth();
    int totalH = jPanel_ecgsignal.getHeight();
    
    // Mode Diagnosis atau Monitoring
    int actualCols = "Diagnosis".equals(currentMode) ? 1 : layoutCols;
    int actualRows = "Diagnosis".equals(currentMode) ? 1 : layoutRows;
    
    int colWidth = totalW / actualCols;
    int rowHeight = totalH / actualRows;
    
    // Reset logic
    if (xGraph >= colWidth) {
        resetBackground();
        xGraph = 0;
    }
    
    g2.setColor(Color.GREEN);
    
    if ("Monitoring".equals(currentMode)) {
        boolean[] effectiveLeadAvailable = new boolean[12];
        int realLeadCount = 0;
        for (int i = 0; i < 12; i++) {
            boolean available;
            if (leadAvailabilityKnown) {
                available = leadAvailable[i];
            } else {
                available = i < processedData.size()
                        && processedData.get(i) != null
                        && processedData.get(i).length > 0;
            }
            effectiveLeadAvailable[i] = available;
            if (available) realLeadCount++;
        }

        for (int i = 0; i < 12; i++) { // SELALU loop 12 lead untuk tampilan
            // Hitung posisi grid
            int colIndex = (actualCols == 1) ? 0 : i / actualRows;
            int rowIndex = (actualCols == 1) ? i : i % actualRows;
            
            int xOffset = colIndex * colWidth;
            int yBase = (rowIndex * rowHeight) + (rowHeight / 2);
            
            // --- HITUNG SINYAL BERDASARKAN LEAD YANG TERSEDIA ---
            int signalY = 0;
            boolean shouldDraw = false;
            
            if (isFileLoaded && !leadsData.isEmpty()) {
                if (effectiveLeadAvailable[i]) {
                    if (i < processedData.size()) {
                        double[] data = processedData.get(i);
                        if (data != null && currentDataIndex < data.length) {
                            signalY = (int) (data[currentDataIndex] * -25.0 * currentGainMultiplier);
                            shouldDraw = true;
                        }
                    }
                } 
                // Jika lead tidak tersedia, GENERATE dari lead yang ada (hanya untuk demo/visual) kayanyua di bagian inideh
                else {
                    Double valI = null;
                    Double valII = null;
                    Double valIII = null;
                    if (processedData.size() > 0 && processedData.get(0) != null && processedData.get(0).length > 0) {
                        int idx = currentDataIndex % processedData.get(0).length;
                        valI = processedData.get(0)[idx];
                    }
                    if (processedData.size() > 1 && processedData.get(1) != null && processedData.get(1).length > 0) {
                        int idx = currentDataIndex % processedData.get(1).length;
                        valII = processedData.get(1)[idx];
                    }
                    if (processedData.size() > 2 && processedData.get(2) != null && processedData.get(2).length > 0) {
                        int idx = currentDataIndex % processedData.get(2).length;
                        valIII = processedData.get(2)[idx];
                    }
                    if (valIII == null && valI != null && valII != null) {
                        valIII = valII - valI;
                    }

                    if (valI != null && valII != null) {
                        if (i == 3) { // aVR = -(I + II)/2
                            signalY = (int) (-(valI + valII) / 2.0 * -25.0 * currentGainMultiplier);
                            shouldDraw = true;
                        } else if (i == 4 && valIII != null) { // aVL = (I - III)/2 
                            signalY = (int) ((valI - valIII) / 2.0 * -25.0 * currentGainMultiplier);
                            shouldDraw = true;
                        } else if (i == 5 && valIII != null) { // aVF = (II + III)/2 
                            signalY = (int) ((valII + valIII) / 2.0 * -25.0 * currentGainMultiplier);
                            shouldDraw = true;
                        } else if (i >= 6 && i <= 11) { // V1-V6 demo dari WCT
                            double wct = (valI + valII) / 3.0;
                            double chestProxy = valII;
                            double scale = 0.7 + 0.05 * (i - 6);
                            signalY = (int) ((chestProxy - wct) * -25.0 * currentGainMultiplier * scale);
                            shouldDraw = true;
                        }
                    }

                    if (!shouldDraw) {
                        // Jika tidak ada cukup lead untuk kalkulasi, beri sinyal kosong
                        signalY = 0;
                        shouldDraw = true;
                    }
                }
            }
            
            if (!shouldDraw) signalY = 0;
            int currentY = yBase + signalY;
            
            // --- GAMBAR GARIS ---
            int drawX_Now = xGraph + xOffset;
            int drawX_Prev = (xGraph - currentSpeedStep) + xOffset;
            
            if (xGraph > 0) {
                g2.drawLine(drawX_Prev, lastY[i], drawX_Now, currentY);
                
                // === LOGIKA GAMBAR P-T-R WAVE ===
                int targetLead = (leadsData.size() > 1) ? 1 : 0;
                
                if (i == targetLead && isFileLoaded && xGraph > 0) {
                    if (showRWave && cachedRIndices.contains(currentDataIndex)) {
                        g2.setColor(Color.RED);
                        g2.fillOval(drawX_Now - 4, currentY - 4, 8, 8);
                        g2.drawString("R", drawX_Now, currentY - 10);
                        g2.setColor(Color.GREEN);
                    }
                    else if (showPWave && cachedPIndices.contains(currentDataIndex)) {
                        g2.setColor(Color.YELLOW);
                        g2.fillOval(drawX_Now - 3, currentY - 3, 6, 6);
                        g2.drawString("P", drawX_Now, currentY - 15);
                        g2.setColor(Color.GREEN);
                    }
                    else if (showTWave && cachedTIndices.contains(currentDataIndex)) {
                        g2.setColor(Color.CYAN);
                        g2.fillOval(drawX_Now - 3, currentY - 3, 6, 6);
                        g2.drawString("T", drawX_Now, currentY - 15);
                        g2.setColor(Color.GREEN);
                    }
                }
            }
            
            lastY[i] = currentY;
            
            // --- LABEL LEAD ---
            if (xGraph <= currentSpeedStep) {
                g2.setColor(Color.WHITE);
                String label = getLeadName(i);
                
                // Beri indikasi jika lead simulasi (bukan dari alat)
                if (!effectiveLeadAvailable[i]) {
                    label = label + "*"; // Tanda bintang untuk lead simulasi
                    g2.setColor(Color.YELLOW); // Warna kuning untuk lead simulasi
                } else {
                    g2.setColor(Color.WHITE); // Warna putih untuk lead real
                }
                
                g2.drawString(label, xOffset + 5, yBase + 5);
                g2.setColor(Color.GREEN);
            }
        }
        
       
        if (xGraph <= currentSpeedStep) {
        }
    } else {
        // --- MODE DIAGNOSIS ---
        int signalY = 0;
        if (isFileLoaded && !leadsData.isEmpty()) {
            int targetIndex = (processedData.size() == 1) ? 0 : 1;
            if (targetIndex < processedData.size()) {
                double[] data = processedData.get(targetIndex);
                if (data != null && currentDataIndex < data.length) {
                    signalY = (int) (data[currentDataIndex] * -150.0 * currentGainMultiplier);
                }
            }
        }
        
        int yBase = totalH / 2;
        int currentY = yBase + signalY;
        
        if (xGraph > 0) {
            g2.drawLine(xGraph - currentSpeedStep, lastY[0], xGraph, currentY);
        }
        
        lastY[0] = currentY;
        
        if (xGraph <= currentSpeedStep) {
            g2.setColor(Color.WHITE);
            g2.drawString("Lead II (Signal Classification View)", 10, 20);
            g2.setColor(Color.GREEN);
        }
    }
    
    // Increment Index Data
    if (isFileLoaded && !leadsData.isEmpty() && leadsData.get(0) != null) {
        currentDataIndex++;
        if (currentDataIndex >= leadsData.get(0).length) currentDataIndex = 0;
    }
    
    // Increment X
    xGraph += currentSpeedStep;
    refreshCounter++;
    
    if (refreshCounter >= 20) {
        updateAutoHR();
        refreshCounter = 0;
    }
}
// --- WINNING SOLUTION: OTOMATISASI HR ---
private void updateAutoHR() {
    // 1. Cek Ketersediaan Data
    if (leadsData == null || leadsData.isEmpty()) return;

    // Default Lead II
    int targetIndex = 1; 
    if (leadsData.size() == 1) targetIndex = 0;
    
    double[] sourceSignal = leadsData.get(targetIndex); // Ambil raw data
    double[] signalToAnalyze;
    
    // 2. Logika Pengambilan Data (File vs Live)
    if (isFileLoaded) {
        // A. MODE FILE: Gunakan seluruh data yang ada
        signalToAnalyze = sourceSignal.clone();
        
        // (Opsional) Apply Filter yang sedang aktif agar HR akurat
        // Kita gunakan logika simple saja: Jika Notch ON, filter Notch.
        if (isNotchOn && notchFreq > 0) {
            signalToAnalyze = ECGFilters.applyNotchFilter(signalToAnalyze, currentFs, notchFreq);
        }
        
    } else if (jrecord.isSelected()) {
        // B. MODE LIVE RECORDING: Gunakan "Sliding Window" (10 Detik Terakhir)
        // Agar ringan dan real-time.
        
        int windowSeconds = 10;
        int windowSamples = (int) (windowSeconds * currentFs);
        
        // Pastikan data minimal 3 detik agar bisa deteksi puncak
        if (writeIndex < (3 * currentFs)) return; 
        
        // Tentukan titik potong (Start - End)
        int endIndex = writeIndex;
        int startIndex = Math.max(0, endIndex - windowSamples);
        int length = endIndex - startIndex;
        
        signalToAnalyze = new double[length];
        System.arraycopy(sourceSignal, startIndex, signalToAnalyze, 0, length);
        
        // Filter Notch Quick (Agar tidak berat di CPU saat live)
        if (isNotchOn && notchFreq > 0) {
            signalToAnalyze = ECGFilters.applyNotchFilter(signalToAnalyze, currentFs, notchFreq);
        }
        
    } else {
        // Tidak ada file dan tidak sedang merekam
        return; 
    }

    // 3. Hitung HR Menggunakan Analyzer
    try {
        ECGAnalyzer liveAnalyzer = new ECGAnalyzer(signalToAnalyze, currentFs, qtcFormula);
        double bpm = liveAnalyzer.getHRAvg(); // Dapatkan BPM rata-rata dari window tsb
        
        // 4. Update Tampilan
        if (bpm > 0) {
            jlblHR.setText(String.format("%.0f", bpm));
            
            // Indikator Warna
            if (bpm < 60) jlblHR.setForeground(Color.BLUE);
            else if (bpm > 100) jlblHR.setForeground(Color.RED);
            else jlblHR.setForeground(new Color(0, 153, 0));
        }
    } catch (Exception e) {
        System.out.println("Auto HR Error: " + e.getMessage());
    }
}

// --- METHOD: BACKGROUND ANALYZER FOR VISUALIZATION ---
// Dipanggil saat: 1. File Uploaded, 2. Record Stop, 3. Filter Berubah
private void updateWaveMarkers() {
    // Safety Check
    if (leadsData == null || leadsData.isEmpty()) return;
    
    // Pilih Lead II (Index 1) atau Lead I (Index 0) sebagai referensi marker
    int targetIndex = (leadsData.size() > 1) ? 1 : 0;
    
    // Ambil data yang sudah ter-filter (processedData)
    if (processedData.isEmpty() || processedData.size() <= targetIndex) return;
    double[] signal = processedData.get(targetIndex);

    // Jalankan Analyzer (Hanya logic, tidak buka window)
    // Gunakan Fs dan Formula yang sedang aktif
    ECGAnalyzer visualAnalyzer = new ECGAnalyzer(signal, currentFs, qtcFormula);
    
    // Simpan hasilnya ke memori dashboard
    cachedPIndices = visualAnalyzer.getPIndices();
    cachedTIndices = visualAnalyzer.getTIndices();
    cachedRIndices = visualAnalyzer.getRIndices();
    
    System.out.println("Visual Markers Updated -> P: " + cachedPIndices.size() + 
                       ", T: " + cachedTIndices.size() + ", R: " + cachedRIndices.size());
}

// --- METHOD HELPER: RESET LAYAR & GAMBAR GRID ---
    private void resetBackground() {
    xGraph = 0; // HAPUS INI DARI SINI. 
    // Biarkan drawLiveECG yang mengatur reset xGraph. 
    // resetBackground tugasnya hanya membersihkan gambar.
    
    Graphics g = jPanel_ecgsignal.getGraphics();
    if (g == null) return;
    
    int w = jPanel_ecgsignal.getWidth();
    int h = jPanel_ecgsignal.getHeight();

    g.setColor(Color.BLACK);
    g.fillRect(0, 0, w, h);

    // Gambar Grid Kecil (50px) - Tetap digambar di kedua mode
    if (jon.isSelected()) {
        g.setColor(new Color(50, 50, 50)); 
        for (int i = 0; i < w; i += 50) g.drawLine(i, 0, i, h);
        for (int i = 0; i < h; i += 50) g.drawLine(0, i, w, i);
        
        // --- REVISI START: Gambar Pembatas Kolom HANYA jika Monitoring ---
        if ("Monitoring".equals(currentMode)) {
            g.setColor(Color.GRAY);
            int colWidth = w / layoutCols; // Gunakan layoutCols asli user
            for (int c = 1; c < layoutCols; c++) {
                g.drawLine(c * colWidth, 0, c * colWidth, h);
            }
        }
    }
    }


  private String getLeadName(int i) {
    if (i == 0) return "I";
    if (i == 1) return "II";
    if (i == 2) return "III";
    if (i == 3) return "aVR";
    if (i == 4) return "aVL";
    if (i == 5) return "aVF";
    if (i == 6) return "V1";
    if (i == 7) return "V2";
    if (i == 8) return "V3";
    if (i == 9) return "V4";
    if (i == 10) return "V5";
    if (i == 11) return "V6";
    return "Unknown";
}
    // --- METHOD BARU: HITUNG ULANG FILTER ---
// Method ini dipanggil saat Upload CSV atau Klik Apply di Settings

// Default tidak ada filter



// B. UBAH LOGIKA FILTERING (Method recalculateFilters)
public void recalculateFilters() {
    // 1. Cek Data Kosong
    if (leadsData == null || leadsData.isEmpty()) return;

    // 2. Bersihkan penampung data
    processedData.clear();

    double fs = this.currentFs; 

    // 3. Loop Proses Filter
    for (double[] rawSignal : leadsData) {
        double[] signalToProcess = rawSignal.clone();

        // --- REVISI START: LOGIKA FILTER ---
        
        // 1. Notch Filter
        // Hanya jalan jika Toggle ON DAN Frekuensi bukan 0/Invalid
        if (isNotchOn && notchFreq > 0) {
            signalToProcess = ECGFilters.applyNotchFilter(signalToProcess, fs, notchFreq);
        }

        // 2. Filter Utama (Bandpass / Low / High / None)
        if ("Low-pass".equals(filterType)) {
            signalToProcess = ECGFilters.applyMovingAverage(signalToProcess, 5);
        } else if ("High-pass".equals(filterType)) {
            signalToProcess = ECGFilters.applyHighPass(signalToProcess, fs);
        } else if ("Bandpass".equals(filterType)) {
            // HANYA JIKA "Bandpass" YANG DIPILIH SECARA EKSPLISIT
            signalToProcess = ECGFilters.applyBandpass(signalToProcess, fs);
        } else {
            // JIKA PILIHANNYA "-" (STRIPE), MAKA TIDAK ADA FILTER (RAW)
            // Do Nothing (Signal tetap original/raw)
        }
        
        // --- REVISI END ---

        // 3. Filter EMG
        if (isEmgOn) {
            signalToProcess = ECGFilters.applyMovingAverage(signalToProcess, 10);
        }

        // Simpan Hasil
        processedData.add(signalToProcess);
    }

    System.out.println("Filters Recalculated! Fs: " + fs + ", Mode: " + filterType + ", Leads: " + processedData.size());
    updateWaveMarkers();
}

// ============================================================
// ========= PYTHON INTEGRATION METHODS (NEW SECTION) =========
// ============================================================

/**
 * Analyzes ECG data using Python backend and displays results.
 * This method extracts 216-sample windows, sends them to the Python server,
 * and displays prediction results.
 */
public void analyzewithPython() {
    // 1. Validate data availability
    if (!isFileLoaded || leadsData == null || leadsData.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please upload ECG CSV file first!");
        return;
    }
    
    // 2. Get target lead (Lead II if available, else Lead I)
    int targetIndex = (leadsData.size() > 1) ? 1 : 0;
    double[] sourceSignal = leadsData.get(targetIndex);
    
    // 3. Apply current filters
    double[] filteredSignal = sourceSignal.clone();
    if (isNotchOn && notchFreq > 0) {
        filteredSignal = ECGFilters.applyNotchFilter(filteredSignal, currentFs, notchFreq);
    }
    if ("Low-pass".equals(filterType)) {
        filteredSignal = ECGFilters.applyMovingAverage(filteredSignal, 5);
    } else if ("High-pass".equals(filterType)) {
        filteredSignal = ECGFilters.applyHighPass(filteredSignal, currentFs);
    } else if ("Bandpass".equals(filterType)) {
        filteredSignal = ECGFilters.applyBandpass(filteredSignal, currentFs);
    }
    
    // 4. Extract 216-sample window for prediction
    double[] predictionSignal = ECGPythonClient.extractSignalWindow(filteredSignal, 0);
    if (predictionSignal == null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Signal too short! Need at least 216 samples.");
        return;
    }
    
    // 5. Calculate RR intervals
    double[] rrIntervals = ECGPythonClient.calculateRRIntervals(filteredSignal, currentFs);
    
    // 6. Send to Python backend (in background thread to avoid blocking UI)
    Thread pythonThread = new Thread(() -> {
        try {
            // Check Python server connection
            if (!ECGPythonClient.testConnection()) {
                javax.swing.JOptionPane.showMessageDialog(MainDashboard.this,
                    "Error: Python server not running.\n" +
                    "Please start the Flask server:\n" +
                    "python3 modelekg.py",
                    "Connection Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Send prediction request
            ECGPythonClient.PredictionResult result = ECGPythonClient.predictECG(
                predictionSignal, 
                rrIntervals[0], 
                rrIntervals[1]
            );
            
            // Display result in analyze panel
            javax.swing.SwingUtilities.invokeLater(() -> {
                displayPredictionResult(result);
            });
            
        } catch (Exception e) {
            javax.swing.SwingUtilities.invokeLater(() -> {
                javax.swing.JOptionPane.showMessageDialog(MainDashboard.this,
                    "Python prediction error:\n" + e.getMessage(),
                    "Prediction Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            });
        }
    });
    pythonThread.setDaemon(true);
    pythonThread.start();
}

    private void displayPredictionResult(ECGPythonClient.PredictionResult result) {
        // ════════════════════════════════════════════════════════════════════════════════════════════
        // REFACTORED FLOW (per RefactorUIUX.md):
        // Step 1: Run Python analysis (done before this method)
        // Step 2: Show Health Report dialog IMMEDIATELY
        // Step 3: User clicks "OK" in Health Report
        // Step 4: Open Detailed Metrics Panel (analyzepanel)
        // ════════════════════════════════════════════════════════════════════════════════════════════
        
        // --- STEP 1: Gather patient and classification data ---
        String patientName = txtname.getText();
        String patientID = jtxtID.getText();
        String patientSex = txtsex.getText();
        String patientBirthdate = jtxtBirthdate2.getText();
        String patientAge = jtxtAge2.getText();
        String patientHeight = jtxtHeight2.getText();
        String patientWeight = jtxtWeight2.getText();
        
        String classificationLabel = result.getLabel() != null ? result.getLabel() : "Unknown";
        String classificationCode = result.prediction != null ? result.prediction : "?";
        double confidence = result.confidence;
        String riskLevel = result.getRiskLevel();
        
        // --- STEP 2: Generate Health Advice ---
        // Build patient context for Gemini
        String patientContext = buildPatientContext(patientAge, patientSex, patientHeight, patientWeight, riskLevel);
        String healthAdvice = GeminiHealthAdvisor.generateAdvancedHealthAdvice(
            classificationCode,
            confidence,
            patientContext
        );
        
        // Update MainDashboard health advice text box
        // --- STEP 3: Build and Show Health Report Dialog ---
        StringBuilder healthReport = new StringBuilder();
        healthReport.append(healthAdvice).append("\n\n");
        healthReport.append("⚠ Consult a cardiologist for clinical evaluation.");
        
        // Also update MainDashboard health advice text box
        updateHealthAdviceBox(healthReport.toString());
        
        // Show Health Report with OK button - user must click OK to proceed
        int userChoice = javax.swing.JOptionPane.showOptionDialog(
            this,
            healthReport.toString(),
            "Patient Health Report - ECG Analysis Complete",
            javax.swing.JOptionPane.DEFAULT_OPTION,
            javax.swing.JOptionPane.INFORMATION_MESSAGE,
            null,
            new String[]{"OK - View Detailed Metrics"},
            "OK - View Detailed Metrics"
        );
        
        // --- STEP 4: If user clicked OK, open Detailed Metrics Panel ---
        if (userChoice == 0 || userChoice == javax.swing.JOptionPane.CLOSED_OPTION) {
            // Create and configure the analyze panel
            analyzepanel analyzeWindow = new analyzepanel(this, true);
            analyzeWindow.setLocationRelativeTo(this);
            
            // Pass COMPLETE patient information to analyzepanel
            analyzeWindow.setPatientInfoComplete(
                patientName, patientID, patientSex, patientBirthdate,
                patientAge, patientHeight, patientWeight,
                classificationLabel, confidence, riskLevel
            );
            
            // Cache the health advice in analyzepanel for "View Health Advice" button
            try {
                java.lang.reflect.Method m = analyzeWindow.getClass().getMethod("cacheHealthAdvice", String.class);
                m.invoke(analyzeWindow, healthAdvice);
            } catch (NoSuchMethodException ignored) {
                // analyzepanel doesn't expose cacheHealthAdvice; proceed without caching
            } catch (Exception ex) {
                logger.warning("cacheHealthAdvice invocation failed: " + ex.getMessage());
            }
            
            // Calculate and set metrics for display
            try {
                int targetIndex = (leadsData.size() > 1) ? 1 : 0;
                double[] signal = leadsData.get(targetIndex);
                
                double dataWindow = signal.length / currentFs;
                int estimatedRPeaks = (int)(dataWindow * 1.2);
                int pPeaks = estimatedRPeaks;
                int tPeaks = estimatedRPeaks;
                int hrAvg = (int)(estimatedRPeaks / dataWindow * 60);
                double rrAvg = (dataWindow / estimatedRPeaks) * 1000;
                
                analyzeWindow.setPythonResults(
                    estimatedRPeaks, pPeaks, tPeaks,
                    hrAvg, rrAvg,
                    classificationLabel, confidence * 100, dataWindow,
                    qtcFormula  // Pass the QTc formula from Settings
                );
            } catch (Exception e) {
                System.out.println("Error calculating metrics: " + e.getMessage());
            }
            
            // Show the Detailed Metrics Panel
            analyzeWindow.setVisible(true);
        }
    }
    
    /**
     * Helper method to build patient context string for Gemini health advice
     */
    private String buildPatientContext(String ageStr, String sex, String heightStr, String weightStr, String riskLevel) {
        int age = 0;
        int height = 0;
        int weight = 0;
        
        try { age = Integer.parseInt(ageStr.trim()); } catch (Exception e) { /* ignore */ }
        try { height = Integer.parseInt(heightStr.trim()); } catch (Exception e) { /* ignore */ }
        try { weight = Integer.parseInt(weightStr.trim()); } catch (Exception e) { /* ignore */ }
        
        double bmi = 0;
        String bmiCategory = "Unknown";
        if (height > 0 && weight > 0) {
            bmi = (weight * 10000.0) / (height * height);
            if (bmi < 18.5) bmiCategory = "Underweight";
            else if (bmi < 25) bmiCategory = "Normal";
            else if (bmi < 30) bmiCategory = "Overweight";
            else bmiCategory = "Obese";
        }
        
        return "Risk level: " + riskLevel +
               ", Age: " + age +
               ", Sex: " + (sex != null && !sex.isEmpty() ? sex : "N/A") +
               ", BMI: " + String.format("%.1f", bmi) +
               " (" + bmiCategory + ")";
    }

/**
 * Batch analysis of multiple ECG windows using Python backend.
 * Useful for continuous ECG monitoring with predictions at regular intervals.
 * 
 * @param windowSize Size of each window in samples (typically 216)
 * @param overlapPercent Overlap between windows in percentage (0-90)
 */
public void batchAnalyzeWithPython(int windowSize, int overlapPercent) {
    if (!isFileLoaded || leadsData == null || leadsData.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please upload ECG CSV file first!");
        return;
    }
    
    if (windowSize != 216) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Window size must be 216 samples for the model!");
        return;
    }
    
    // Get target lead
    int targetIndex = (leadsData.size() > 1) ? 1 : 0;
    double[] sourceSignal = leadsData.get(targetIndex);
    
    // Calculate window stride
    int stride = (int) (windowSize * (1 - overlapPercent / 100.0));
    if (stride < 1) stride = windowSize / 2;
    
    // Extract windows
    java.util.List<double[]> windows = new java.util.ArrayList<>();
    java.util.List<double[]> rrIntervals = new java.util.ArrayList<>();
    
    for (int i = 0; i + windowSize <= sourceSignal.length; i += stride) {
        double[] window = ECGPythonClient.extractSignalWindow(sourceSignal, i);
        if (window != null) {
            windows.add(window);
            double[] rr = ECGPythonClient.calculateRRIntervals(window, currentFs);
            rrIntervals.add(rr);
        }
    }
    
    if (windows.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Cannot extract 216-sample windows from signal!");
        return;
    }
    
    // Run batch prediction in background
    Thread batchThread = new Thread(() -> {
        try {
            if (!ECGPythonClient.testConnection()) {
                throw new Exception("Python server not running");
            }
            
            java.util.List<ECGPythonClient.PredictionResult> results = 
                ECGPythonClient.batchPredict(windows, rrIntervals);
            
            // Count predictions by type
            java.util.Map<String, Integer> counts = new java.util.HashMap<>();
            for (ECGPythonClient.PredictionResult r : results) {
                counts.put(r.prediction, counts.getOrDefault(r.prediction, 0) + 1);
            }
            
            // Display summary
            javax.swing.SwingUtilities.invokeLater(() -> {
                StringBuilder summary = new StringBuilder();
                summary.append("Batch Analysis Results (").append(results.size()).append(" windows):\n\n");
                counts.forEach((pred, count) -> {
                    summary.append(pred).append(": ").append(count).append(" windows\n");
                });
                
                javax.swing.JOptionPane.showMessageDialog(this, summary.toString(),
                    "Batch Prediction Summary", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            });
            
        } catch (Exception e) {
            javax.swing.SwingUtilities.invokeLater(() -> {
                javax.swing.JOptionPane.showMessageDialog(MainDashboard.this,
                    "Batch analysis error:\n" + e.getMessage(),
                    "Analysis Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            });
        }
    });
    batchThread.setDaemon(true);
    batchThread.start();
}

private void trimArrays() {
        if (writeIndex == 0) return;
        
        // Buat list baru untuk hasil potong
        java.util.List<double[]> trimmedLeads = new java.util.ArrayList<>();
        java.util.List<double[]> trimmedProcessed = new java.util.ArrayList<>();
        
        for (int i = 0; i < 12; i++) {
            double[] fullData = leadsData.get(i);
            double[] realData = new double[writeIndex];
            // Copy hanya data yang terisi (sampai writeIndex)
            System.arraycopy(fullData, 0, realData, 0, writeIndex);
            
            trimmedLeads.add(realData);
            trimmedProcessed.add(realData.clone()); // Copy ke processed juga
        }
        
        // Replace list utama
        leadsData = trimmedLeads;
        processedData = trimmedProcessed;
        
        // Jalankan filter ulang terhadap data yang baru saja direkam
        recalculateFilters();
        updateWaveMarkers();
    }

// Method penghubung untuk dipanggil dari Settings.java
public void applySettingsFromDialog() {
    recalculateFilters(); // Hitung ulang
}

/**
 * Enforces the correct state of the Analyze button based on current mode and data availability.
 * RULES:
 * - Monitoring Mode: btnAnalyze ALWAYS disabled
 * - Classification Mode + Data Loaded: btnAnalyze enabled
 * - Classification Mode + No Data: btnAnalyze disabled
 * 
 * Call this method whenever:
 * 1. Mode changes (via Settings)
 * 2. Data is loaded (CSV upload or recording stops)
 * 3. Recording starts (disable button)
 */
private void enforceButtonState() {
   // Tombol Analyze HANYA boleh aktif jika:
    // Mode = Classification DAN Data sudah ada DAN tidak sedang merekam
    boolean isClassification = "Classification".equals(currentMode);
    boolean hasData = isFileLoaded && leadsData != null && !leadsData.isEmpty();
    boolean isNotRecording = !jrecord.isSelected();

    if (isClassification && hasData && isNotRecording) {
        btnAnalyze.setEnabled(true);
        btnAnalyze.setToolTipText("Click to run analysis");
    } else {
        btnAnalyze.setEnabled(false);
        // Berikan feedback ke user kenapa tombol mati
        if (!isClassification) {
            btnAnalyze.setToolTipText("Switch to Classification Mode to enable analysis");
        } else {
            btnAnalyze.setToolTipText("Upload CSV or record data first");
        }
    }
}

// --- INNER CLASS: DITARUH DISINI (DILUAR METHOD APAPUN) ---
// REPLACE YOUR processParsedData METHOD WITH THIS:

 private void processParsedData() {
    while (!queueString.isEmpty()) {
        String data = queueString.poll();
        if (data == null) continue;

        String[] parts = data.split(";");
        if (!jrecord.isSelected()) continue;

        try {
            // ═══════════════════════════════════════════════════════════════
            // PROTOCOL F8: F8;I;II;III;aVR;aVL;aVF;C1;Resp;StatusError;NoUrut
            // parts[0] = "F8"
            // parts[1-8] = data untuk 8 lead
            // parts[9] = StatusError
            // parts[10] = NoUrut (counter)
            // ═══════════════════════════════════════════════════════════════
            if (parts[0].equals("F8") && parts.length >= 11) { // Perlu 11 field (0-10)
                if (writeIndex < MAX_SAMPLE) {
                    // Update Leads 0-7 (I, II, III, aVR, aVL, aVF, C1, Respiration)
                    for (int i = 0; i < 8; i++) {
                        String valString = parts[i + 1]; // parts[1] s/d parts[8]
                        double val = 0.0;
                        
                        if (valString != null && !valString.isEmpty() && !valString.equals("")) {
                            try {
                                double raw = Double.parseDouble(valString);
                                // Normalisasi: PS410 mengirim 0-255, baseline 127
                                val = (raw - 127.0) / 40.0; 
                            } catch (NumberFormatException ex) {
                                val = 0.0; 
                            }
                        }
                        
                        // Mapping ke array leadsData:
                        // Index 0-6: I, II, III, aVR, aVL, aVF, C1 (V1)
                        // Index 7: Respiration (kita skip atau simpan terpisah)
                        if (i < 7) { // Simpan hanya lead ECG, skip respiration
                            leadsData.get(i)[writeIndex] = val;
                            processedData.get(i)[writeIndex] = val;
                        }
                    }
                    
                    writeIndex++; 
                }
            }
            // ═══════════════════════════════════════════════════════════════
            // PROTOCOL FE: FE;C2;C3;C4;C5;C6;StatusError
            // parts[0] = "FE"
            // parts[1-5] = data untuk 5 chest leads (V2-V6)
            // parts[6] = StatusError
            // ═══════════════════════════════════════════════════════════════
            else if (parts[0].equals("FE") && parts.length >= 7) { // Perlu 7 field (0-6)
                // FE datang SETELAH F8, jadi kita tulis ke index SEBELUMNYA
                int targetIndex = (writeIndex > 0) ? writeIndex - 1 : 0;
                
                // C2-C6 adalah lead index 7-11 (V2-V6)
                for (int i = 0; i < 5; i++) {
                    String valString = parts[i + 1]; // parts[1] s/d parts[5]
                    double val = 0.0;
                    
                    if (valString != null && !valString.isEmpty() && !valString.equals("")) {
                        try {
                            double raw = Double.parseDouble(valString);
                            val = (raw - 127.0) / 40.0;
                        } catch (NumberFormatException ex) { 
                            val = 0.0; 
                        }
                    }
                    
                    // Simpan ke index 7-11 (V2-V6)
                    leadsData.get(7 + i)[targetIndex] = val;
                    processedData.get(7 + i)[targetIndex] = val;
                }
            }
            // ═══════════════════════════════════════════════════════════════
            // PROTOCOL FC: Status dan Channel Info (skip untuk data plotting)
            // ═══════════════════════════════════════════════════════════════
            else if (parts[0].equals("FC")) {
                // FC berisi info status channel, bukan data waveform
                // Untuk sekarang kita skip
                System.out.println("FC Status received");
            }
            // ═══════════════════════════════════════════════════════════════
            // PROTOCOL FF: Electrode status untuk chest leads (skip)
            // ═══════════════════════════════════════════════════════════════
            else if (parts[0].equals("FF")) {
                // FF berisi info electrode chest, bukan data waveform
                System.out.println("FF Electrode status received");
            }
            
        } catch (Exception e) {
            System.out.println("Parse error for: " + data + " | " + e.getMessage());
        }
    }
}
public void setIndentity(String id) {
        // This is called when the device sends device info (0xFD)
    System.out.println("Device ID: " + id);
        // Optional: Update a label on your UI
        // jlblStatus.setText("ID: " + id); 
}


private final boolean[] leadAvailable = new boolean[12];
private boolean leadAvailabilityKnown = false;

// lah kok udah ada? emg dr awal udh ada kan ya?  (tp yg kebaca tetep 3 doang) ngga ada tadi di projectt 

public void setStatusChannels(int[] channels) {

    // Status lead real-time dari paket FC/FF

    // channels index:
    // 0..6 = I, II, III, aVR, aVL, aVF, C1(V1)
    // 8..12 = C2..C6 (V2..V6)  [lihat ThrdParsingECG]
    if (channels == null || channels.length < 13) return;

    leadAvailable[0] = channels[0] == 1;  // I
    leadAvailable[1] = channels[1] == 1;  // II
    leadAvailable[2] = channels[2] == 1;  // III
    leadAvailable[3] = channels[3] == 1;  // aVR
    leadAvailable[4] = channels[4] == 1;  // aVL
    leadAvailable[5] = channels[5] == 1;  // aVF
    leadAvailable[6] = channels[6] == 1;  // V1 (C1)
    leadAvailable[7] = channels[8] == 1;  // V2 (C2)
    leadAvailable[8] = channels[9] == 1;  // V3 (C3)
    leadAvailable[9] = channels[10] == 1; // V4 (C4)
    leadAvailable[10] = channels[11] == 1;// V5 (C5)
    leadAvailable[11] = channels[12] == 1;// V6 (C6)

    leadAvailabilityKnown = true;
}

public void setElektrode(int[] electrodes) {
        // Called for electrode status
        // System.out.println("Electrode Status Update");
}

// --- INNER CLASS: PEMBACA DATA SERIAL (Versi jSerialComm) ---
// --- PERBAIKAN INNER CLASS: SERIAL PORT READER ---
// --- INNER CLASS: PEMBACA DATA SERIAL (Versi jSerialComm) ---
class SerialPortReader implements SerialPortDataListener {

    @Override
    public int getListeningEvents() { 
        // Memberitahu library: "Panggil saya kalau ada data masuk"
        return SerialPort.LISTENING_EVENT_DATA_AVAILABLE; 
    }

    @Override
    public void serialEvent(SerialPortEvent event) {
        // Safety check: Pastikan eventnya benar data available
        if (event.getEventType() != SerialPort.LISTENING_EVENT_DATA_AVAILABLE) return;
        
        // Baca data byte yang masuk
        byte[] newData = new byte[serialPort.bytesAvailable()];
        int numRead = serialPort.readBytes(newData, newData.length);
        
        if (numRead > 0) {
            // Ubah byte ke String
            String receivedData = new String(newData);
            serialBuffer += receivedData; 

            // --- LOGIKA PARSING DATA (Split per baris) ---
            int lineEndIndex;
            // Selama ada karakter "Enter" (\n), berarti ada satu baris data utuh
            while ((lineEndIndex = serialBuffer.indexOf("\n")) != -1) {
                // Ambil satu baris bersih
                String line = serialBuffer.substring(0, lineEndIndex).trim();
                // Buang baris itu dari buffer (biar gak dibaca ulang)
                serialBuffer = serialBuffer.substring(lineEndIndex + 1);

                // Pisahkan data CSV (titik koma)
                String[] values = line.split(";"); 
                
                // Pastikan tombol Record aktif dan data lengkap 12 kolom
                if (values.length == 12 && jrecord.isSelected()) {
                    if (writeIndex < MAX_SAMPLE) {
                        for (int i = 0; i < 12; i++) {
                            try {
                                double val = Double.parseDouble(values[i]);
                                leadsData.get(i)[writeIndex] = val;
                                processedData.get(i)[writeIndex] = val;
                            } catch (NumberFormatException e) { 
                                // Abaikan jika data corrupt/bukan angka
                            }
                        }
                        // Geser index array ke kanan setelah 1 baris (12 lead) selesai direkam
                        writeIndex++;
                    }
                }
            } // End While Loop
        }
    }
}
// -----------------------------------------------------------
public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyze;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnsettings;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_cbGain;
    private javax.swing.JComboBox<String> jComboBox_cbSpeed;
    private javax.swing.JComboBox<String> jComboBox_port;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel_ecgsignal;
    private javax.swing.JPanel jPanel_panelpatient2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnDownload;
    private javax.swing.JButton jbtnfreeze;
    private javax.swing.JTextField jlblHR;
    private javax.swing.JTextField jlblStatus;
    private javax.swing.JToggleButton jon;
    private javax.swing.JToggleButton jrecord;
    private javax.swing.JTextField jtxtAge2;
    private javax.swing.JTextField jtxtBirthdate2;
    private javax.swing.JTextField jtxtHeight2;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextArea jtxtNotes2;
    private javax.swing.JTextField jtxtWeight2;
    private javax.swing.JButton jupload;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsex;
    // End of variables declaration//GEN-END:variables

   
}





